### ISSUE TITLE
Detecting a column as type DECIMAL(0) in Oracle

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#106]
While exporting from Oracle a column type was detected as type `DECIMAL(0)` which is invalid taking into consideration the valid patterns for SQL types which mandate the size of a DECIMAL to be greater than 0.

**Comment by chalkos** [comment]
Maybe including information about the conversion of types to SQL99 and SQL2003 will help fix issues like this one in the future.
