### ISSUE TITLE
Missing UNIQUE constraint

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#11]
When roud-trip testing from PostgreSQL to SIARD and back again, UNIQUE constraints on columns are missing. This may occur with other DBMS but it was only verified in PostgreSQL.

**Comment by chalkos** [comment]
When roundtrip testing the world database on PostgreSQL,

```CONSTRAINT country_continent_check CHECK ((((((((continent = 'Asia'::text) OR (continent = 'Europe'::text)) OR (continent = 'North America'::text)) OR (continent = 'Africa'::text)) OR (continent = 'Oceania'::text)) OR (continent = 'Antarctica'::text)) OR (continent = 'South America'::text)))```

is lost. (see #120)

**Comment by luis100** [comment]
@chalkos Is this done now that #120 is closed?

**Comment by chalkos** [comment]
Exporting constraints to DBMSes is not a requirement for DBPTK.
This case is similar to [exporting default values to DBMSes](https://github.com/keeps/db-preservation-toolkit/issues/177#issuecomment-486157045).

I'm closing this issue as it is not relevant.

note: in this case the unique constraint is still saved in the SIARD file, it is only lost when exporting to a DBMS which is ok from a db preservation standpoint.
