### ISSUE TITLE
SIARD-DK export module option details is wrong

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/db-preservation-toolkit#114]
Using suggested pattern for export folder name
```
Export module: siard-dk
    -ef, --export-folder=value    (required) Path to SIARDDK archive folder. Archive folder must match the pattern AVID.[A-ZÆØÅ]{2,4}.[1-9][0-9]*
```
generates an error stating that the folder name does not match expression (also here there is a lack of coherence 'pattern' vs. 'expression')
```
INFO [15:50:28] Translating database: mysql to siard-dk
ERROR [15:50:28] Error while importing/exporting
                 Archive folder name must match the expression AVID.[A-ZÆØÅ]{2,4}.[1-9][0-9]*.[1-9][0-9]*
```

**Comment by chalkos** [comment]
duplicate. see #79

**Comment by chalkos** [comment]
@hsilva-keep sorry, it's related but not a duplicate.
@andreaskring could you look into this?

**Comment by chalkos** [comment]
@hsilva-keep the patterns seem to differ. The documentation reads `AVID.[A-ZÆØÅ]{2,4}.[1-9][0-9]*` but the error reads `AVID.[A-ZÆØÅ]{2,4}.[1-9][0-9]*.[1-9][0-9]*` have you tried both?

**Comment by hsilva-keep** [comment]
@chalkos Firstly I've tried the pattern suggested by the dbptk usage/help information. Which lead to the error I've posted before. And doing as suggested in the error message, i.e. using the other pattern, indeed I was able to run the command with success.

**Comment by PhillipTommerholt** [comment]
The title describes the problem well:
SIARD-DK export module option details is wrong.

@hsilva-keep the pattern you succeded with: AVID.[A-ZÆØÅ]{2,4}.[1-9][0-9]*.[1-9][0-9]* is indeed the correct pattern according to SIARDDK, so the change will have to be made in the description of the export module options.

**Comment by hsilva-keep** [comment]
@PhillipTommerholt #80 is indeed related but only states that the description should be improved whilest I'm stating that the description is wrong.

**Comment by chalkos** [comment]
fixed by @andreaskring
