### ISSUE TITLE
MySQL import problem

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#115]
I experience problems in the import from MySQL.

I have successfully imported/exported via another tool, so it could be a bug in db-preservation-toolkit.

> ERROR [10:44:36] Error while importing/exporting
                 SQL error while conecting
                 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'list of products' at line 1
> 

See logfile:
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/69593/dbptk-app.log.txt)

**Comment by chalkos** [comment]
I have narrowed down the problem to view's names not being escaped in mysql. I'll fix it in a while.

**Comment by chalkos** [comment]
If the created SIARD2 file is converted to a MySQL database, the process does not finish and outputs errors similar to the ones in #120 and #131
