### ISSUE TITLE
SIARDDK should escape identifiers in queries

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#116]
> I have tried to make an export of Northwind database to SIARDDK via DB Preservation Toolkit, but it failed due to one of the table names in Northwind.
> 
> Table Order details contains a space, which is not allowed in the SIARDDK format for table names (or column names, primary keys etc. for that matter - Standard SQL feature for identifiers).
> 
> A solution is to make a change in the import/export process so that all names come in double quotes ( table “Order details”).
Originally reported by @PhillipTommerholt

log file: [dbptk-app.txt](https://github.com/keeps/db-preservation-toolkit/files/69782/dbptk-app.txt)

**Comment by andreaskring** [comment]
@PhillipTommerholt This issue should be fixed now. If you would like a version of the code that handles this now (before the change gets merged into the master branch), you can get it from the the magenta-aps forked project like this:

$ git clone https://github.com/magenta-aps/db-preservation-toolkit.git
$ cd db-preservation-toolkit
$ git fetch origin develop
$ git checkout develop
 and then run
$ mvn clean package

**Comment by chalkos** [comment]
fixed by @andreaskring
