### ISSUE TITLE
Error while exporting candidate key: check constraint condition cannot be null

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#118]
The problem happens when trying to convert MS SQL Server to SIARD and is related to the existence of constraints in the database. Removing the constraints allowed the conversion process to successfully complete.

Log file: [dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/80583/dbptk-app.log.txt)
Reported by @PhillipTommerholt

**Comment by chalkos** [comment]
@PhillipTommerholt this is pretty old... do you mind checking if this has been fixed or if this problem still exists in the latest version?

And also, is this blocking a pilot?

**Comment by PhillipTommerholt** [comment]
This issue is fixed. 
![untitled](https://cloud.githubusercontent.com/assets/15984159/16581113/13ff5bdc-42a8-11e6-803e-bdaec52289ad.png)

(I just checked).
