### ISSUE TITLE
Unable to complete round-trip test in PostgreSQL (9.5.0) with sample world databse.

### ISSUE THREAD

**Issue by ThomasKristensen** [keeps/db-preservation-toolkit#120]
The steps carried out / to reproduce is included below.
The output - including the error messages produced by dptkl - is included in the attached pdf-file (console-out.pdf).
[console-out.pdf](https://github.com/keeps/db-preservation-toolkit/files/97973/console-out.pdf)

    #!/bin/bash
	    
    java -version
    psql --version
    mvn -version
    
    #import world db to local PostgreSQL-server
    wget http://pgfoundry.org/frs/download.php/527/world-1.0.tar.gz
    gunzip world-1.0.tar.gz
    tar -xvf world-1.0.tar
    createdb world ENCODING=UTF8
    psql --dbname=world --file=./dbsamples-0.1/world/world.sql

    #Fetch and build dbptk (latest commit on master brach at the time of this writing)
    
    git clone https://github.com/keeps/db-preservation-toolkit.git
    cd db-preservation-toolkit
    git reset --hard e2a627c65f3f1f930a0e297b40c6ac13e8f3e0e2
    mvn clean package
    
    #Generate siard file based on world sample database.
    java -jar dbptk-core/target/dbptk-app-2.0.0-rc3.2.4.jar -i postgresql  --import-hostname=localhost -idb world -iu tk -ip test123  -e siard-1 -ide -ef ../world-siard.siard
    #(Try to) export siard file back to postgresql - world2 database
    java -jar dbptk-core/target/dbptk-app-2.0.0-rc3.2.4.jar -e postgresql  --export-hostname=localhost -edb world2 -eu tk -ep test123  -i siard-1 -ede -if ../world-siard.siard

**Comment by chalkos** [comment]
It's a known bug. Will fix it soon.

**Comment by chalkos** [comment]
@ThomasKristensen there has been some progress on this issue: on the line https://github.com/keeps/db-preservation-toolkit/commit/62b986433a76d8fd0146020cd5296353597daddb#diff-47b87bae78eacd712f1c3089d1ad1ad8R241 I added a roundtrip test that uses the World database and MySQL. The conversion completes although some characteristics are not correctly converted (I'll create issues to address those), so the roundtrip test assertion is failing and that's why it is in a comment. I'll create a test for postgresql to fix this issue.

**Comment by chalkos** [comment]
The conversion completes, although there are a couple differences.

```
--
-- Name: country; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE country (
...
    gnp numeric(10,2),
    gnpold numeric(10,2),
...
    CONSTRAINT country_continent_check CHECK ((((((((continent = 'Asia'::text) OR (continent = 'Europe'::text)) OR (continent = 'North America'::text)) OR (continent = 'Africa'::text)) OR (continent = 'Oceania'::text)) OR (continent = 'Antarctica'::text)) OR (continent = 'South America'::text)))
);
```
becomes
```
--
-- Name: country; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE country (
...
    gnp numeric,
    gnpold numeric,
...
);
```

So ```numeric(10,2)``` becomes ```numeric``` and the constraint is lost.
But that belongs in another issue, since converting the "world" database from postgresql to siard2 and back to postgresql works.
