### ISSUE TITLE
Option to pick which tables that will be exported to the SIARD-file.

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#126]
Requirement for Pilot2, E-ARK.

**Comment by jmaferreira** [comment]
Dear @PhillipTommerholt,

Have you tried to manage which tables are exported by means of the permissions associated with the credentials used?

**Comment by chalkos** [comment]
@PhillipTommerholt To address this I'm going to develop a module that creates a list of tables contained in the source database, this list can be saved to a file. The file could be manually edited and would be used by the SIARD module to filter the tables that are exported.

Do you think this solution is adequate?

**Comment by PhillipTommerholt** [comment]
@chalkos 
Yes, that sounds fine. 
@andreaskring is also making a module for SIARDDK in which the user can choose which CLOB-tables/CLOB-columns that will be extracted as external files. Does it make sense that the two of you talk about this solution?

**Comment by andreaskring** [comment]
@PhillipTommerholt Yes, I think that I will be able to used the module that @chalkos will be developing. I will talk to him about this
