### ISSUE TITLE
Arrays should be supported

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#129]
For DBMS that support array datatypes, they should be exported to SIARD 2 and imported from SIARD 2 into another DBMS.

**Comment by Laurira** [comment]
It appears to have problems with tsvector as well.
Possibility of incomplete type definition: Could not determine SQL2008 type for tsvector
Should it be handled in separate issue?

**Comment by chalkos** [comment]
I read something about it and it seems that tsvector is a list of *normalized* words. I guess they fit in this issue, thanks for bringing it to my attention.

If this proves to be very different from an array, I'll close this issue when I complete array support and create a new one for tsvector.
