### ISSUE TITLE
Support for comments on columns on export to PostgreSQL(?)

### ISSUE THREAD

**Issue by ThomasKristensen** [keeps/db-preservation-toolkit#130]
Support for comments on columns on export to PostgreSQL would be a nice enhancement. (I'm aware that it might be low priority for now). 

The syntax (which seems to be stable across versions) for setting a comment on a column is :

```
COMMENT ON COLUMN public.city.name IS 'Test comment'
```
I haven't been able to find a way to include the comment in the same DDL statement creating the table/column (which is probably why it is not implemented yet in dptkl, right?).

ref: http://www.postgresql.org/docs/current/static/sql-comment.html

**Comment by BorisDomajnko** [comment]
The SIARD column level metadata "description" ("The meaning and content of the column") could hold this value. Maybe some database is well documented using the column comments as shown above. Unfortunately there is no standard SQL way for column comments as far as I can see. From archival point of view they can be a usefull (or sometimes only) information, and for restoring the database the comment could be implemented where possible.

**Comment by chalkos** [comment]
@ThomasKristensen could you confirm that this is a postgresql feature that is not implemented?
I think I previously mistaken it by something else (therefore adding SIARD-DK label and assigning @andreaskring, which may have been a mistake).

@BorisDomajnko there may be specific ways (for each DBMS) to save comments and I agree that they should be saved (and restored) if they are present.

**Comment by ThomasKristensen** [comment]
@chalkos @andreaskring  Please notice, that I'm no longer associated with the project though a contract with Magenta, so it would probably be best if you redirect questions to Andreas. Thanks.

**Comment by chalkos** [comment]
superseded by #174
