### ISSUE TITLE
Problem with importing postgresql table with uppercase name

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#143]
The name of one of the tables is (as displayed by pgAdmin):
      CREATE TABLE regust."upravna_enotaOLD"
I get this error with dbptk-app-2.0.0-rc3.2.5.jar: 
     INFO [09:37:37] Translating database: postgresql to siard-2
     INFO [09:37:37] STARTED: Getting the database structure.
     ERROR [09:37:39] Error while importing/exporting
                 SQL error while conecting
                 ERROR: relation "regust.upravna_enotaold" does not exist
                   Position: 22

Should we have an option in the tool to define whether a table name is case sensitive or not? I doubt that one default solution will suit all.

Boris Domajnko

**Comment by chalkos** [comment]
There is probably some way to determine if the DBMS is case sensitive or not. This may be specific to the DBMS (and in this case it would be coded specifically for each DBMS in its import/export modules) or specific to the database (in this case there must be some query that can be run to find out if dbptk should be case sensitive).

Nonetheless this is a problem in postgreSQL module(s) and will be fixed.

**Comment by BorisDomajnko** [comment]
Regarding case sensitive table and column names: everything is possible in the production. For archiving a decision is needed whether you find out the setting and usage automatically or simply use a siard parameter, or you opt for one solution only. This may be important for the use in the DIP. For example, we get some queries as part of ingest documentation and we reuse them for DIP, and then it will not be the same to use select * from tablename or select * from "tableNAME".

**Comment by chalkos** [comment]
I think this was closed by mistake.

**Comment by BorisDomajnko** [comment]
Additional information using test option: -e list-tables   (the name of the table is "Tabela1"):
 Connection error while importing/exporting
                 SQL error while conecting
                 ERROR: relation "public.tabela1" does not exist

**Comment by chalkos** [comment]
Thanks. This is further proof that the problem resides in the PostgreSQL import module.

**Comment by BorisDomajnko** [comment]
Sent by mail. It was created as default application with/by MS Office Access (Fixed Assests Inventory) and it is used just to increase the variety of test examples. Output of  -i microsoft-access  -e list-tables
 
PUBLIC.Stiki
PUBLIC.Zadeve
UCA_METADATA.PROP
UCA_METADATA.TABLES
UCA_METADATA.COLUMNS

**Comment by BorisDomajnko** [comment]
2.0.0-beta4.3: the problem still occurs.
It works if I rename Tabela1 to tabela1

**Comment by chalkos** [comment]
@BorisDomajnko thanks for the info.

Personal notes: This seems to occur for PostgreSQL modules and now #163 describes a very similar problem. If case-sensitivity is fixed for foreign keys creation, then #163 can also be marked as fixed.

**Comment by chalkos** [comment]
Fixed in #216

Turns out the problem was not the table case, but using a schema other than public.
