### ISSUE TITLE
Unexpected exception, reason cannot be determined / problem with PostgreSQL integer[]

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#145]
I have identified the problematic table from larger database and copied it to a new schema. The error is reproduced here but there is no meaningful java exception information which would be very helpful here. 

INFO [11:09:20] Translating database: postgresql to siard-2
INFO [11:09:20] STARTED: Getting the database structure.
INFO [11:09:20] FINISHED: Getting the database structure.
INFO [11:09:20] STARTED: Getting data of table: public.arhiv_log
ERROR [11:09:20] Unexpected exception

The first column in the table was defined as id integer[] and fortunately the column contained no data. So I removed  this column and it worked then! In this case the issue was resolved but speaking generally (besides the error message above): is array allowed here? 

Boris Domajnko

**Comment by chalkos** [comment]
Array support is still under development (see #129) nevertheless the error is not clear and the output should be improved to provide more information.

For detailed information on the error, could you check the file dbptk-app.log (it should be in the directory where the ```java -jar ...``` command was executed) and copy the last part here? It's the part after `ERROR [11:09:20] Unexpected exception` that starts with `DEBUG`. If you ran dbptk after submitting the bug report, try to locate the text `11:09:20` in the file (that should take you to the part you reported in this issue).

**Comment by BorisDomajnko** [comment]
(id is integer[] ....)

DEBUG 2016-03-01 10:28:07,340 (PostgreSQLJDBCImportModule) query: SELECT id, tabela, polje, vrednost, vrsta, sprememba, uporabnik, datum FROM regust.arhiv_log
DEBUG 2016-03-01 10:28:07,343 (JDBCImportModule) Parsing array of subtype UnsupportedDataType
ERROR 2016-03-01 10:28:07,343 (Main) Unexpected exception
DEBUG 2016-03-01 10:28:07,344 (Main) Unexpected exception
java.lang.NullPointerException
	at com.databasepreservation.modules.siard.out.content.SIARD2ContentExportStrategy.writeComposedCell(SIARD2ContentExportStrategy.java:160)
