### ISSUE TITLE
Travis builds sometimes fail for java 7

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#152]
This started with #144

Sample failed build: https://travis-ci.org/keeps/db-preservation-toolkit/jobs/115039545

**Comment by chalkos** [comment]
@ThomasKristensen @andreaskring the builds are failing and passing on java 7 for no obvious reason. Sometimes they pass, sometimes they do not. I think this may be due to machine resources limitations (RAM, simultaneous open streams/files, etc).

I'll try turning off parallel testing to see if this has any effect on the build.
If it does not help, I will disable the siarddk tests and will enable them when they are passing (so that master is always passing to serve as a good base for other branches).

In the sample build in the issue description I found out that DK tests are only being run on the 4th thread, I `grep`ed for that and added the bottom part of the file, containing the `Killed` part.

This is what I got: [dktesting.txt](https://github.com/keeps/db-preservation-toolkit/files/172590/dktesting.txt)

The last dk-related line reads:
`[pool-1-thread-4] DEBUG 2016-03-10 11:53:32,698 (SIARDDKContentImportStrategy) begin parse of xml-file:[Tables/table1/table1.xml], using xsd [Tables/table1/table1.xsd]`

The last line before the `Killed` part reads:

`[pool-1-thread-2] DEBUG 2016-03-10 11:53:37,649 (JDBCExportModule) Executing table creation batch`

Which is 5 seconds after starting the xml file parsing. The first one took 14 seconds. Maybe there is some resource leak somewhere in there.

**Comment by andreaskring** [comment]
@chalkos Thanks for the info. It will be interesting to see what happens, when you turn off parallel testing - hope this helps

**Comment by chalkos** [comment]
In a new branch (bf-travis-test-problem) based on master (at https://github.com/keeps/db-preservation-toolkit/commit/809dd1b89c2d75db8e7182673b2f1346b12118d7) I removed parallel testing and this is the travis failing build https://travis-ci.org/keeps/db-preservation-toolkit/builds/116090040

Note that it is failing for all tested java versions, sometimes after successfully parsing the table1.xml file once, other times it is parsed twice before the error occurs.

I will disable the siard-dk tests for now for reasons mentioned above.

**Comment by chalkos** [comment]
Is there a good reason to use this [TestFileIndexFileStrategy.java#L36](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-core/src/test/java/com/databasepreservation/siarddk/TestFileIndexFileStrategy.java#L36) instead of getting a tmp folder using NIO2 like in [Roundtrip.java#L144](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-core/src/test/java/com/databasepreservation/testing/integration/roundtrip/Roundtrip.java#L144)? (see also deleting it: [Roundtrip.java#L178](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-core/src/test/java/com/databasepreservation/testing/integration/roundtrip/Roundtrip.java#L178))

After closing this issue I will suggest a few changes to the siarddk tests in the pull request (the seem to be a little out of sync with the existing tests).

**Comment by chalkos** [comment]
I disabled the tests by adding these lines [dbptk-core/testng.xml, lines 42 to 71](https://github.com/keeps/db-preservation-toolkit/commit/f48e6bd076f9b26bb4320522ed4ce0279a30bc1b#diff-aea83caed764c986aa5b53ae7dc51ccdR42)
If you have those lines you may want to remove them in the pull request.

**Comment by andreaskring** [comment]
@chalkos This can be closed now

**Comment by chalkos** [comment]
Right. Thanks.
