### ISSUE TITLE
Cannot add foreign key (Postgre -> Mysql)

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#154]
Description: I created SIARD-2 file from one of our Postgre databases. After I tried to import that file to my localhost mysql database. All the tables were nicely migrated but there were also some foreign keys on some tables which resulted an error when imported.

Steps required to reproduce the bug:

I have a POSTGRE database that I exported to SIARD-2
SIARD-2 file has a table autor with foreign key fk_a_isik
See the following file metadata.xml from metadata.zip (github do not allow xml files to upload)
[metadata.zip](https://github.com/keeps/db-preservation-toolkit/files/168763/metadata.zip)

When I try to import that file to the mysql database I get an error
ERROR [11:15:01] Error handleing foreign key (next exception)
                 Cannot add foreign key constraint
ERROR [11:15:01] Error description:
                 Cannot add foreign key constraint
ERROR [11:15:01] Error while importing/exporting
                 Error creating foreign keys
                 Cannot add foreign key constraint

I also attached the log file. Search "error" from it and you will get to the right place.
[baasTestfisOlgaArvutis_Import_dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/168767/baasTestfisOlgaArvutis_Import_dbptk-app.log.txt)

**Comment by chalkos** [comment]
@BorisDomajnko Also reported a similar problem occurring on relations:
`ERROR: relation "relation-name" already exists`

**Comment by chalkos** [comment]
@Laurira Could you try to convert the siard2 file to mysql to a database named `public`?

**Comment by BorisDomajnko** [comment]
My problem was explained, but I have opened #161.

**Comment by Laurira** [comment]
Seems that the issue will not occur when I try to export my file to the database that is names "public" (different from the initial name).

But why does it rename the foreign key? For example I have a foreign key fki_auvik_fond in PostgreSQL but after the import/export I will have dbpres_14599397187611 in MySQL.

**Comment by Laurira** [comment]
Also I have index fki_auvik_fond in PostgreSQL but after the import/export I will have dbpres_14599397187611 in MySQL. Why is the index named the same as the foreign key?

**Comment by chalkos** [comment]
> Seems that the issue will not occur when I try to export my file to the database that is names "public" (different from the initial name).

Ok. As I suspected. Could you try the conversion again with version beta4.0? (to a database that the name is **not** public)

> But why does it rename the foreign key? For example I have a foreign key fki_auvik_fond in PostgreSQL but after the import/export I will have dbpres_14599397187611 in MySQL.

To avoid conflicts or foreign key names that are not compatible with the target DBMS.

> Also I have index fki_auvik_fond in PostgreSQL but after the import/export I will have dbpres_14599397187611 in MySQL. Why is the index named the same as the foreign key?

I can't recall the reason. Is it bad that they have the same name? Aren't they related.

**Comment by Laurira** [comment]
With beta4.0 I got an error

ERROR [12:12:44] Failed to open lob at ./schema1/table4/lob37/record1105.txt
                 File "./schema1/table4/lob37/record1105.txt" is missing in container
ERROR [12:12:44] Unexpected exception


Same SIARD file works with previous version.
[dbptk-app.log_Beta4.txt](https://github.com/keeps/db-preservation-toolkit/files/214665/dbptk-app.log_Beta4.txt)

I attached the log file.

**Comment by chalkos** [comment]
Could you try using version 4.0 to create a new SIARD file and then use this file for the conversion?

**Comment by Laurira** [comment]
You were right, now it worked. Thanks
