### ISSUE TITLE
Use NullCell in SIARD DK

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#157]
@andreaskring @ThomasKristensen I made a change to standardize the way NULL cells are represented.

i.e.: Using a `new SimpleCell(someid, null)` to represent a NULL cell of textual type is now **deprecated** and `new NullCell(id)` should be used. (other NULL cells that are not of textual type should also be represented by NullCell)

This change was made to make it easier to declare and identify NULL cells across import/export modules.
The issue exists so we don't forget about this.
I hope you are not against this change, let me know your opinion on this.

**Comment by andreaskring** [comment]
@chalkos This can be closed

**Comment by chalkos** [comment]
thanks
