### ISSUE TITLE
An option for resetting the log file

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#159]
Description: Usually I would work with one database and repeat the steps after resolving the issues. In this case I do not need the old log file. I suggest a new option: --overwrite-logfile   so I will not need to delete the dbptk-app.log

(dbptk-app-2.0.0-rc3.2.5.jar)

**Comment by BorisDomajnko** [comment]
Maybe also an option for the name of the log file? I am testing with more databases and I need to keep a separate log for each of them - and I have to rename them manually.

**Comment by chalkos** [comment]
I would like to avoid adding *global* (ie: non-module) command line parameters. There is `-h, --help` and adding more options to fit special needs like this one may lead to polluting the help text with options that are rarely used.

I don't know if you are on windows or linux, but if you are on linux, how about a script like this one:

```
#!/bin/bash

JARFILE="dbptk-app-2.0.0-beta4.0.jar"

echo "running command: java \"-Dfile.encoding=UTF-8\" -jar $JARFILE ${@:2}"
java "-Dfile.encoding=UTF-8" -jar "$JARFILE" ${@:2}

echo "renaming log file to '$1.log.txt'"
mv dbptk-app.log.txt "$1.log.txt"
```

usage: `scriptname logname dbptk-args`
The first argument is the name of the log file (using `name` would rename `dbptk-app.log.txt` to `name.log.txt` after running DBPTK.
For the following arguments use the ones you would use for dbptk:
`-i mysql -ih ... -e siard-2 -ef somefile`

**Comment by BorisDomajnko** [comment]
I have been on both platforms and for test execution I can accept this solution, thanks.
BTW, my PostgreSQL is running on FreeBSD but I do not run .jar there.

**Comment by chalkos** [comment]
I'm glad it worked.
