### ISSUE TITLE
CREATE DATABASE vs. CREATE SCHEMA (PostgreSQL)

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#161]
Description: In my DBMS I see more databases and each is a collection of schemas. Each database  is created with CREATE DATABASE ... They can host various registers, test versions,,... Each of them has own access rights. The explicit application with its own name space is then created below database with CREATE SCHEMA. For example, I create a database  "siard" as a playground for testing all siard packages. I expected that each restored database from siard will appear there as a schema. But they are created on the root level - each siard package becomes a new database. With the concept of schemas I could restore more versions of one archived database as more schemas at the same time. 

Steps required to reproduce the bug:

1. CREATE DATABASE "eark_test"
2. java ...  -e postgresql -edb eark_test.siard  ...
3. I get a new database "eark_test.siard" and the tables are below default schema Public

Attach the dbptk-app.log.txt file below.
DEBUG 2016-03-18 10:09:30,510 (JDBCExportModule) Loading JDBC Driver org.postgresql.Driver
DEBUG 2016-03-18 10:09:30,525 (JDBCExportModule) Getting connection
DEBUG 2016-03-18 10:09:30,525 (JDBCExportModule) Connected
INFO 2016-03-18 10:09:30,541 (JDBCExportModule) Handling database structure
INFO 2016-03-18 10:09:30,541 (JDBCExportModule) Handling schema structure public
INFO 2016-03-18 10:09:30,541 (JDBCExportModule) Handling table structure arhiv_log

**Comment by chalkos** [comment]
Just so we are on the same page:

> In mysql a database is a schema. The two words can be used interchangeably in most commands. For instance, you could say create database dbname, or create schema dbname and achieve the same result.
> 
> Postgres has a different concept of schema. It is a namespace that contains tables, functions, operators and data types. It is essentially a layer between the database and the tables. In postgres, a database may contain many schemas and those schemas may contain the same tables or different ones. The "public" schema is the default schema in a database.

*from* http://www.estelnetcomputing.com/index.php?/archives/10-Database-vs.-Schema-Definition-in-Mysql-vs.-Postgres.html

Each schema on postgres will correspond to a database on mysql, those are limitations of the DBMS, not dbptk. A database on mysql will be converted to a postgres database on the default schema (public) because mysql does not have the notion of a schema.

> For example, I create a database "siard" as a playground for testing all siard packages. I expected that each restored database from siard will appear there as a schema. But they are created on the root level - each siard package becomes a new database.

This is the intended behaviour because of mysql limitations, at least for now.

@luis100 do you have any comments on this?

**Comment by chalkos** [comment]
I need more information to determine if this is an e-ark requirement or it is really working as intended.

**Comment by BorisDomajnko** [comment]
I agree we should not use any product related features or limitations, however the SIARD format should still be able to hold as much information as possible in some generic format, and the targeted DIP database should be able to support the available features it can handle. If we stick to the level of the database for input and output, this might be ok for the beginning.
I have tested creation of siard file (database with two schemas: public, sche_testb) 
INFO [13:06:11] FINISHED: Getting data of table: public.tabela1
INFO [13:06:11] STARTED: Getting data of table: sch_testb.users
so it seems the schema name is the attribute of the table. I suggest we wait for further tests or real life scenarios from other users and then we will see.

**Comment by chalkos** [comment]
> the SIARD format should still be able to hold as much information as possible in some generic format

It does. SIARD formats can contain a database with many schemas and each schema of those schemas can have many tables. What is missing?

**Comment by BorisDomajnko** [comment]
It seems I am using schemas as databases. Is it possible to restore more databases into one target database and I get more schemas? I think this is how it works now because I managed to get duplicates (relation already exists). In this case my use case might work.

**Comment by chalkos** [comment]
This is not a bug, but a request for a new feature. I created a new issue with the intent of providing clearer details on what is expected from the new feature.

Please confirm that it is suitable for your use case: #164
