### ISSUE TITLE
Extracting siard-2: problem with year 207

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#171]
Description: There is a wrong date in the table (207 instead of 2007). I cannot restore the table from siard2 file. Manually I was able to enter such a year into the PostgreSQL table therefore I assume siard is checking the syntax.
If the user has wrong values and this is not resolved before the ingest, we should be able to restore such tables as they are.

dbptk-app-2.0.0-beta4.0.jar:

1. MS Access -> siard-2
2. siard-2 -> PostgreSQL

INFO [14:27:52] Exporting data for PUBLIC.Izpiti
ERROR [14:27:52] line: 1; column: 280530; cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
                 cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
ERROR [14:27:52] line: 1; column: 280530; cvc-type.3.1.3: The value '207-10-03T23:00:00.00Z' of element 'c3' is not valid.
                 cvc-type.3.1.3: The value '207-10-03T23:00:00.00Z' of element 'c3' is not valid.
ERROR [14:27:52] Unexpected exception
                 207-10-03T23:00:00.00Z

Attach the dbptk-app.log.txt file below.
DEBUG 2016-04-01 14:27:52,680 (JDBCExportModule) timestamp after: 2002-06-21 00:00:00.0
DEBUG 2016-04-01 14:27:52,680 (JDBCExportModule) timestamp after: 2003-09-26 00:00:00.0
ERROR 2016-04-01 14:27:52,686 (SAXErrorHandler) line: 1; column: 280530; cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
                 cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
DEBUG 2016-04-01 14:27:52,686 (SAXErrorHandler) line: 1; column: 280530; cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
                 cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 280530; cvc-datatype-valid.1.2.1: '207-10-03T23:00:00.00Z' is not a valid value for 'dateTime'.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)

**Comment by luis100** [comment]
This is simply a formatting problem, date time is on the format `[-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm]` so the date should be formatted as: `0207-10-03T23:00:00.00Z`.

**Comment by BorisDomajnko** [comment]
2.0.0-beta4.3: bad dates are now ok. In PostgreSQL I get 0209-11-10.

**Comment by chalkos** [comment]
@BorisDomajnko That is great. It was a problem with MS SQL Server, but apparently it affected other DBMS (in this case PostgreSQL). Could you just verify that the date value is correct? ie, MS Access date `0209-11-10` produces date `0209-11-10` in the SIARD file.

And is this date really supposed to mean the year 209 and not something else like year 2009? It may still be a formatting problem like Luis said.

**Comment by BorisDomajnko** [comment]
These are typos in the application with no input control in the GUI, a few dates were entered as for example 209 instead of 2009. During the ingest we just take what we get.

**Comment by chalkos** [comment]
Fix confirmed. Closing the issue.
