### ISSUE TITLE
Support exporting database, schema, table and column descriptions

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#174]
Descriptive metadata present in database, schema, table and column is not being exported.

If an element is missing from this list, it means that the DBMS does not provide a way to add descriptive metadata (like comments) to that element (or I could not find it).

**MySQL**
- via JDBC
    - [x] Table
    - [x] Column
    - [x] Function / procedure

**PostgreSQL**
- via JDBC
    - [x] TABLE
    - [x] COLUMN
    - [x] VIEW
- via querying system tables directly
    - [x] DATABASE
    - [x] CONSTRAINT
    - [x] FOREIGN KEY
    - [x] FUNCTION
    - [x] ROLE
    - [x] SCHEMA
    - [x] TRIGGER

creating: http://www.postgresql.org/docs/9.1/static/sql-comment.html
retrieving: http://www.postgresql.org/docs/current/interactive/functions-info.html#FUNCTIONS-INFO-COMMENT-TABLE

**MS SQL Server**
- via querying system tables directly
    - [x] Database
    - [x] Schema
    - [x] Table
    - [x] Column

**Oracle**
- via querying system tables directly
    - [x] Table
    - [x] Column

info: https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_4009.htm

**Comment by chalkos** [comment]
MySQL table and column added in https://github.com/keeps/db-preservation-toolkit/commit/cd2a0eb4dd9d3b510f3d2c30aab621ee3a766606

**Comment by PhillipTommerholt** [comment]
When an element is on the list above but us not ticked off with a :heavy_check_mark: does this mean that DBPTK should be able to export metadata for this element but in the current state can't?

**Comment by chalkos** [comment]
It means that the database supports that kind of descriptive metadata but its extraction from the database is not yet implemented.

**Comment by SaraCharlotta** [comment]
So is extraction of descriptive metadata from tables and columns in MS SQL Server and Oracle something that will be implemented in later versions of DBPTK? Is there a time frame for this?

**Comment by chalkos** [comment]
It will be implemented, but there is currently no time frame for it (as far as I know. @luis100 may know more).

**Comment by luis100** [comment]
Hi @SaraCharlotta, our current customers have not defined this as a priority. There will be a new development sprint soon but the requirements have not yet been defined. So it is still unclear whereas this feature would be part of the next version or postponed further into the future.

**Comment by chalkos** [comment]
Done for all DBMS and descriptive metadata listed.
