### ISSUE TITLE
Default values are lost in conversion to any DBMS

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#177]
Default value information is lost because DBMS export modules do not export this information. ColumnStructure#getDefaultValue() is only used in SIARD export modules.

**Comment by chalkos** [comment]
This is not trivial because a default value in a DBMS may not be supported in a different DBMS.

Possible fix: after creating the table, alter it and add the default values one at a time, skipping them if an error occurs because they are not supported by the target DBMS.

**Comment by BorisDomajnko** [comment]
We do not extract&restore live databases ( or is there such a requirement?).Therefore, if "default" values are already in the package among other data values, why alter db info?

**Comment by chalkos** [comment]
It's not altering db info. It is using the SQL `ALTER TABLE` instruction.

**Comment by luis100** [comment]
@chalkos what is the status of this issue?

**Comment by chalkos** [comment]
Not fixed, but it is not relevant anyway from a database preservation perspective.
Default values are used when **adding** to a database, and DBPTK exports data to DBMSs in order to use DBMS tools to **analyze** the data (where default values have no impact).

For a different use case, exporting the default values would make sense; but since it has no impact on accessing the information that was in the database it is not a requirement for DBPTK. I'm closing this issue as it is not relevant.

note: the default values are still preserved in the SIARD file, which is important.
