### ISSUE TITLE
Date vs. timestamp

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#179]
Description: If the database column holds pure date (without time), it is disturbing to get SELECT output with time like  00:00:00. We could filter this in db viewer but maybe it is better to deal with it sooner.

Steps required to reproduce the bug:

1. MS Access, the date column, values like "1974-07-15"
2. create SIARD-2 package
3. restore to PostgreSQL, columns values are like "1974-07-15 00:00:00"
4. the created column type is "timestamp without time zone", in this case I expected "date"

**Comment by chalkos** [comment]
It appears that MS Access import module is treating DATE type as DATETIME type.

Can you identify in the log (in the conversion from MS Access to SIARD-2), in the part where datatypes are identified, which should look something like this (except with different values):

```
Type name: SMALLINT UNSIGNED
Column size: 5
Decimal digits: 0
Radix: 10
Remarks: 
Default value: null
Index: 1
Is Nullable: false
Is auto increment: true
Calculated type: SimpleTypeNumericExact
ColumnType hash: 481763376
```

Can you identify the type of the column that contains dates? The columns are in the same order as they are in Access and the list of types should be near the table name, so searching the log for the table name should get you in the vicinity of the datatypes debug information.

Knowing the column type in Access may also be helpful to solve this.

**Comment by BorisDomajnko** [comment]
I have checked the Access configuration. It seems that the dptk behaviour is correct, but the problem still exists in the DB viewer. 
In Access all observed fields are defined as Date/Time. When I browse the table the column BirthDate has only date, and in another coulmn I see the timestamp values like "5.8.2011 8:46:27". This means that in such a field I can type "5.8.2011 8:46:27" or only "5.8.2011". When I browse the table I will see the exact entered values. Only in case when I enter "29.5.1957 00:00:00", Access displays "29.5.1957". The funny part is I cannot enter midnight as 24:00:00 is not allowed.
Th original application uses some input format mask and the user wil not see time values (00:00:00).
dptk log:
The solution could be done in db viewer but I do not like it. This is example is PostgreSQL specific:
   SELECT persons."Birth_date",   to_char(persons."Birth_date", 'YYYY-MM-DD')  FROM ...
and it returns "1986-08-01 00:00:00" "1986-08-01"

DEBUG 2016-04-04 14:19:51,217 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 11
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

**Comment by chalkos** [comment]
If Access saves the data as date+time, even if it only displays the date when the time is 00:00:00, dbptk will read the whole date+time. It would not be correct if dbptk removed time if it was 00:00:00, why would it purposely delete correct information it got from the database?

Since you mention db viewer, I think this really is a task for DB viewer, because it is about the data presentation, not its internal storage format. Although even in dbviewer the way to represent midnight would be to include the 00:00:00, omitting that would introduce the same strange behaviour MS Access seems to have: "I cannot enter midnight as 24:00:00 is not allowed." and then there would be no difference between `2016-04-20` (the day, or the whole day) and `2016-04-20 00:00:00` (exactly midnight of 2016-04-20).

**Comment by BorisDomajnko** [comment]
Is "output column formatting" a new functionality request for db viewer then? We try to emulate the original GUI as much as possible under archival circumstances, and this date is an example.

**Comment by chalkos** [comment]
> Is "output column formatting" a new functionality request for db viewer then?

Yes. I believe it should be. Although some more details on the specific formats that should be supported may be necessary. You are welcome to create an issue with this at https://github.com/keeps/dbviewer/issues

I'm closing this issue since this is not a dbptk problem.

**Comment by BorisDomajnko** [comment]
I will not open a feature request. I have found out that I can use a "standard" sql functionality - CAST. But there is some risk that CAST is not supported by some of our target databases.
PostgreSQL example: SELECT
  CAST        (izkaznice."Datum_izdaje" AS DATE), 
  TO_CHAR(izkaznice."Datum_izdaje", 'yyyy-mm-dd'), 
                    izkaznice."Datum_izdaje"

gives:  "2008-02-21";"2008-02-21";"2008-02-21 00:00:00"

There is also FORMAT(column_name,format), but not available on my PostgreSQL. 

Some info also here: https://en.wikibooks.org/wiki/SQL_Dialects_Reference/Functions_and_expressions/Date_and_time_functions
