### ISSUE TITLE
Export to SIARDDK: two problems with suffixed blank characters

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#191]
Description: 

I tried to export Northwind database (on Microsoft SQL Server) to SIARDDK. In some of the tables in Northwind there are suffixed blank characters, and they appear like this after the export:

`<?xml version="1.0" encoding="utf-8"?>
<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema13/table13.xsd table13.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema13/table13.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <row>
    <c1>01581</c1>
    <c2>Westboro\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020</c2>
    <c3>1</c3>
  </row>
  <row>
    <c1>01730</c1>
    <c2>Bedford\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020\u0020</c2>
    <c3>1</c3>
  </row>`

There are two problems with this:

1:
Executive Order 1007 states that:
5.A.2 The content of the individual fields must be cleared of any prefixed and suffixed blank characters.

2:
The escaped \u0020 used for multible spaces is only allowed in SIARD1.0 and in SIARD 2.0, not in SIARDDK (see´Executive Order 1007 5.D.)

Thank you for your time,
Phillip Tømmerholt

**Comment by andreaskring** [comment]
@PhillipTommerholt I will fix this and get back to you

**Comment by andreaskring** [comment]
@PhillipTommerholt Fixed in this branch: https://github.com/magenta-aps/db-preservation-toolkit/tree/issue_191_195

**Comment by PhillipTommerholt** [comment]
this is fixed in beta5.
