### ISSUE TITLE
SIARDDK export: namespaces in xml-tables

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#195]
Description: 
After export the different tables have namespaces that appear like this:

Table1:
`<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema1/table1.xsd table1.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema1/table1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

Table2:
`<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema2/table2.xsd table2.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema2/table2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

The schema will always be schema0 like this:

Table1:
`<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema0/table1.xsd table1.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

Table2:
`<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema0/table2.xsd table2.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

**Comment by andreaskring** [comment]
@PhillipTommerholt Fixed in this branch: https://github.com/magenta-aps/db-preservation-toolkit/tree/issue_191_195

**Comment by PhillipTommerholt** [comment]
This is fixed in beta5.
