### ISSUE TITLE
Invalid XML character (Unicode: 0xb) table XML

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#196]
Description: Error "An invalid XML character (Unicode: 0xb) was found in the element content of the document" appears when converting SIARD2 to MySQL.

By the SIARD2 spec, this character is not required to be escaped, but if it is not escaped the file is not valid XML.

**Comment by andersbonielsen** [comment]
Actually SIARD 2.0 states in G_3.3-3 that Unicode control characters 0-31 "are coded using the solidus ("\") to ensure that the validity of the XML file is guaranteed."
Unfortunately, in the following section G_3.3-4 value 11 is not directly mentioned, only 0-8 and 14-31.
We should notify Hartwig Thomas about this issue.

**Comment by chalkos** [comment]
That is correct. I had some difficulties understanding which characters needed to be escaped.
Should I notify Hartwig Thomas or are you planning on notifying him yourself?

**Comment by chalkos** [comment]
Unicode 0xB and 0xC are also not allowed in XML.

**Comment by andersbonielsen** [comment]
I think you should do it, you found the problem, and Luis and I missed it in the first place.
By the way, to complicate the matter, you cannot state in general that value 11 or 0xB is invalid in XML, it is invalid for XML 1.0, but valid for XML 1.1. But SIARD 2.0 is using XML 1.0 only - (maybe that should also be noted)
