### ISSUE TITLE
MS SQL Server Import module fails for schemas other than 'dbo'

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#199]
Description: 

I am experiencing problems in the microsoft-sql-server import module, at my first task in pilot 1.

It seems that tables with dbo schemas run perfectly, but when you have tables with other schemas (or other prefixes) the import stops.

I have tried to reproduce the problem in Northwind database, where I created an extra table  (se picture from my management studio)
![udklip](https://cloud.githubusercontent.com/assets/15984159/15322603/1b148af4-1c3e-11e6-8c3a-202985fdcff3.PNG)

See log file
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/268177/dbptk-app.log.txt)

(I have tested via cmd that the user I connect with have rights to all schemas and all tables, so it must be a bug in the application)

**Comment by chalkos** [comment]
I will look into this. I changed the title so it is clearer what the issue is about, I hope that's ok.

**Comment by andersbonielsen** [comment]
Yes, it is allright with the change of title, we just wanted to emphasize that this bug is a showstopper for pilot 1.

**Comment by chalkos** [comment]
Ok. To make that clear, I created a label that can now be used to signal issues like this one.
I'm fixing some problems in MS SQL Server and I will fix this one as well for the next release.

**Comment by andersbonielsen** [comment]
Fine, I was about to propose such a label.
We will tell our pilot 1 agency that we are working on getting the rest of their tables exported.

**Comment by jmaferreira** [comment]
@chalkos check to see if its a permissions issue. The user being used to extract the database might not have permissions to read the other schemas.

**Comment by PhillipTommerholt** [comment]
I have tested via cmd that the user I connect with have rights to all schemas and all tables, so it must be a bug in the application. (see last line in original post).

**Comment by PhillipTommerholt** [comment]
Maybe to be more precise (i might have misunderstood you Miguel or not explained myself well enough):

I have tested via sqlcmd (Windows 10) that I can extract data with the same user.
