### ISSUE TITLE
Column type change in MySQL

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#20]
When round-trip testing from MySQL to SIARD and back again, the following column data types changed:
* `tinyint(4)` became `smallint(6)`
* `bigint(20)` became `decimal(19,0)`
* `timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP` became `datetime NOT NULL`
* `tinyint(1)` became `bit(1)`
* `blob` became `longblob`

**Comment by chalkos** [comment]
related to #9

**Comment by chalkos** [comment]
```timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP``` became ```datetime NOT NULL``` is related to #29 (default values). ```ON UPDATE CURRENT_TIMESTAMP``` could probably be stored as a trigger.

**Comment by chalkos** [comment]
These cases are handled in the roundtrip tests, except for default values and triggers, but that is database behavioural metadata (not a top priority). Closing this issue since the "Column type changes in MySQL" are now handled correctly in the roundtrip tests.
