### ISSUE TITLE
Ensure that primary keys are only added after the data

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#205]
An attempt exists to do this on a per-DBMs basis (using DBMS-specific environment variables, connection string parameters, etc), but it does not work for all cases as I noticed MySQL is not ignoring unique checks, even having the unique checks variable set to false for the connection.

**Comment by luis100** [comment]
@chalkos is this done?

**Comment by chalkos** [comment]
Yes. Creating foreign keys has been moved down the migration workflow, so that the keys are created after all data has been exported. This solution is database independent, so it works for all existing and future JDBC-based export modules.
