### ISSUE TITLE
Error converting SIARD2 with multiple schemas to MySQL

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#207]
Description: 
I have a postgre database “VAU” with two schemas „public“ (30 tables) and “vau” (54 tables). I assume that when I run the dbptk on that database then I will get all the tables exported but in the end I  get 72 tables instead of 84.
 
The only errors I get are 175 constraint errors:
168 tell that “Table 'tbl_migration' is already existing”
7 tell that “Table 'vau.tbl_page_article' doesn't exist”. This table really does not exist but there is no error when trying to create that table.
 
I attached the log file. From line 12857 the export begins. As the SIARD file itself is 1,68 GB then I will not share it.

I sent you the log files to the email.

**Comment by chalkos** [comment]
(By email) I have asked to delete both `tbl_migration` tables and try again.

**Comment by chalkos** [comment]
It was the table conflict that was making the following queries fail.
