### ISSUE TITLE
SIARDDK support for LOBs per folder and LOBs folder size

### ISSUE THREAD

**Issue by andersbonielsen** [keeps/db-preservation-toolkit#213]
We need SIARDDK to have some of the same features as SIARD 2.0 regarding support for LOBS stored outside the SIARD archive file.
Appendix D in E-ARK deliverable 3.3 - SIP Pilot specification
http://www.eark-project.com/resources/project-deliverables/51-d33pilotspec
Latest version of spec. (with changes req. by Bruno)
https://docs.google.com/document/d/1FPTm1JIOJkjXX0OFVkPH_T9duAKjv7CD-pAuCTGV0qY/edit#

Parameters needed:
Set limit for folder size - before creating new folder (max total size of files per folder in MB)
equal to **-eelpf** for SIARD 2.0 - default 1 GB
Set limit for folder amount - before creating new folder (max no. of files per folder)
equal to **-eelfs** for SIARD 2.0 

Needed for E-ARK pilot 1
Needed by mid July 2016

**Comment by luis100** [comment]
@chalkos please add milestone to mid July and add this issue to it

**Comment by andreaskring** [comment]
@andersbonielsen I have implemented the feature in [this](https://drive.google.com/file/d/0B8hAEqjI-ScYVUlxdGRGeG50bEk/view?usp=sharing) jar. @PhillipTommerholt Could you please check if the export module is behaving as expected?

**Comment by PhillipTommerholt** [comment]
Yes I will, should I state the same parametres as in SIARD2.0? **-eelpf** and and **-eelfs**

**Comment by andreaskring** [comment]
Almost. Use -elpf and -elfs instead

**Comment by chalkos** [comment]
I think we should keep the arguments consistent. I use `elpf` with the `e` meaning *external* (and the whole thing meaning "external lobs per folder" (this is used `-eelpf` when used with an export module).

Do you also have an argument like this one?
`-eel, --export-external-lobs    (optional) Saves any LOBs outside the siard file.`

**Comment by PhillipTommerholt** [comment]
In SIARDDK there is no SIARD file and BLOBs always have to be extracted, so if there are BLOBs in the database, they will always lie in certain folders in the SIP package.

**Comment by andreaskring** [comment]
In SIARDDK there is not an argument like `-eel`, since, as @PhillipTommerholt mentioned, the LOBs are always external. That is the reason why the first "e" in `-eelpf` is not needed.

**Comment by PhillipTommerholt** [comment]
This works :+1:
