### ISSUE TITLE
Oracle schema/tablespace error.

### ISSUE THREAD

**Issue by mezeijozsef** [keeps/db-preservation-toolkit#215]
Importing SIARD to Oracle, we got some errors last week:
- the tablespace must be exist with the same name as schema
- and the tablespace must be the default for the user

These errors shouldn't be holding the user down, i think these rules/features could use some improvement.

![dbptk-error-v2](https://cloud.githubusercontent.com/assets/19432723/16559615/5fa318cc-41ee-11e6-8ba7-a6fe8c46e8d6.png)

**Comment by chalkos** [comment]
Thank you for your feedback. I will look into this, but the solution it might still be a workaround, because some Oracle features (like tablespaces management) are difficult to control from an external program (like dbptk).

**Comment by chalkos** [comment]
Personal note: maybe I don't need to mess with tablespaces after all: https://community.oracle.com/thread/1116835?tstart=0
