### ISSUE TITLE
Error when importing siard to oracle

### ISSUE THREAD

**Issue by mezeijozsef** [keeps/db-preservation-toolkit#219]
Description: Error when importing siard to oracle
![dbptk-burtmp1](https://cloud.githubusercontent.com/assets/19432723/16583808/475acc54-42b8-11e6-9dc6-03c01c745631.JPG)
Steps required to reproduce the bug:

1. Export BUR_TMP1 Oracle to SIARD 2.0
2. Drop the tables in BUR_TMP1 to get an empty schema - so import can be possible
3. Import this SIARD 2.0 back to BUR_TMP1 Oracle - error

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/347675/dbptk-app.log.txt)

**Comment by chalkos** [comment]
Is this a pilot blocker?

**Comment by mezeijozsef** [comment]
Yes it is part of the pilot.

**Comment by chalkos** [comment]
Ok. thanks for the info.
By the way, this has been fixed in release beta5

**Comment by mezeijozsef** [comment]
There is another error now i just submitted :)
