### ISSUE TITLE
SIARDDK: NullPointerException when handling textual content

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#225]
This is a pilotblocker.

I used beta5.jar on one of our pilot databases (MS SQL Server) and tried to export to SIARDDK. 
I am getting null errors in 3 tables. 

See the first error in a shortened anonymized log:
[Pilotblockernull.pdf](https://github.com/keeps/db-preservation-toolkit/files/351857/Pilotblockernull.pdf)
I do not think that the log points to a certain column, so I am not sure where the error is. (should the log be more detailed?) Therefore I have provided the log details for all the datatypes in the first erroneous table (Datetime, Float, Nvarchar(255)). In the two other problematic tables, datetime is not there.

- Best regards, Phillip

**Comment by andreaskring** [comment]
@PhillipTommerholt This should be fixed now. Could you please check, if it is working in your end (you can use the jar file located here: https://drive.google.com/file/d/0B8hAEqjI-ScYNlVva0RJa01JSkU/view?usp=sharing)

**Comment by PhillipTommerholt** [comment]
Thx! I can give you an answer tomorrow.

**Comment by PhillipTommerholt** [comment]
This is fixed :thumbsup:
