### ISSUE TITLE
microsoft- acess to siard2 fails

### ISSUE THREAD

**Issue by dglab-arquivos** [keeps/db-preservation-toolkit#226]
Description: microsoft- acess to siard2 fails

Steps required to reproduce the bug:

java  "-Dfile.encoding=UTF-8" -jar  dbptk-app-2.0.0-beta5.jar -i  microsoft-access -if bacess.mdb -e siard-2 -ef paisagens.siard2

tried also with beta4.3 and similar error

[dbptk-app.log.txt.zip](https://github.com/keeps/db-preservation-toolkit/files/354066/dbptk-app.log.txt.zip)

Attach the dbptk-app.log.txt file below.

**Comment by chalkos** [comment]
Is there anything about this file that may be problematic? Like being encrypted or partially corrupted.

The error message in the log just mentions an unexpected object while reading the file, which is not very informative, other than the file's contents were not in the correct order or some were missing.

In the meantime I will try to use the latest MS Access conector to create a private release and send it to you by email. Hopefully using the latest version will fix the problem.

**Comment by dglab-arquivos** [comment]
We assume that is a good file.

Tried with other access file, lots of entries ( +- 400k entries) and this is the error:
Converting database structure
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.nio.ByteBuffer.wrap(Unknown Source)
        at java.nio.ByteBuffer.wrap(Unknown Source)

for the moment we don’t have any other access file but will try to get it and make more tests.
Regards.

De: Bruno Ferreira [mailto:notifications@github.com]
Enviada: segunda-feira, 11 de Julho de 2016 09:45
Para: keeps/db-preservation-toolkit <db-preservation-toolkit@noreply.github.com>
Cc: Informatica <informatica@dglab.gov.pt>; Author <author@noreply.github.com>
Assunto: Re: [keeps/db-preservation-toolkit] microsoft- acess to siard2 fails (#226)


Is there anything about this file that may be problematic? Like being encrypted or partially corrupted.

The error message in the log just mentions an unexpected object while reading the file, which is not very informative, other than the file's contents were not in the correct order or some were missing.

In the meantime I will try to use the latest MS Access conector to create a private release and send it to you by email. Hopefully using the latest version will fix the problem.

**Comment by chalkos** [comment]
That is a different problem with a different database. I would like to keep one github issue per problem and so I created a new issue with the info you provided me (#227).

I hope you have received the application version I sent you by email. Were you able to test it with this "paisagens" database?

**Comment by chalkos** [comment]
Status: I have a simpler file containing only the problematic table in my email that I was able to use to reproduce the problem.

Updating to the latest MS Access conector fixed some problems in other tables, so that was also an improvement.

**Comment by chalkos** [comment]
Please try this new version [dbptk-app-2.0.0-beta5-226-2.zip](https://github.com/keeps/db-preservation-toolkit/files/369206/dbptk-app-2.0.0-beta5-226-2.zip). It does not fix the problem itself, but includes information to the producers so they can fix the Ms Access file and try the conversion again.

The problem occurs because the table name contains an `'` (apostrophe) character.
This problem seems to be very hard to fix, so the current solution outputs a message informing that the table name contains invalid characters so the producers can change the table name and try again.

**Comment by dglab-arquivos** [comment]
It seems a fair solution. Done some tests and its ok.

Converting database structure
WARN  Ignoring table 'Unload Worksheet$'_ImportErrors in schema PUBLIC because it constains one of these non-supported characters: '
      Obtaining table structure for PUBLIC.Concelhos


After removing the ' on the table name

Obtaining table structure for PUBLIC.Unload Worksheet$_ImportErrors

Getting contents from table 'PUBLIC.Unload Worksheet$_ImportErrors'
      Total of 568 row(s) processed
      Obtained contents from table 'PUBLIC.Unload Worksheet$_ImportErrors'


$ character works fine in table name.
