### ISSUE TITLE
Unsupported varbinary(max) on MSSQLServer to SIARD conversion

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#23]
When converting from MSSQLServer to SIARD, columns of the type `varbinary(max)` are mapped into SIARD type `BIT VARYING(-8)`, which does not make sense.

**Comment by chalkos** [comment]
Fixed by https://github.com/keeps/db-preservation-toolkit/pull/197/commits/20e822c7cff14779edddf14f44b547cf9a4182ff
