### ISSUE TITLE
MS Access to siard: unsupported collating sort order

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#240]
MS Access file has included mdb. When creating a siard file warnings are reported.

1. main file: Izkaznice_IV_MNZ.mdb, included file: evidenca_2004.mdb
2. java -Xmx1000m -Dfile.encoding=UTF-8 -jar d:\projekti\e-ark\dbptk-app-2.0.0-beta5.jar -i microsoft-access -if Izkaznice_IV_MNZ.mdb -e list-tables -ef out_izk1_tables.txt
2. warnings are on the screen, but I can't see anything in dbptk-app.log.txt

screen error:
      Converting database: microsoft-access to list-tables
      Initializing target database
      Converting database structure
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Firme;Index=0), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Izkaznice;Index=2), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Firme;Index=0), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Izkaznice;Index=2), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Firme;Index=0), making read-only
WARNING:Error in the metadata of the table Izkaznice: table's row count in the metadata is 11279 but 11303 records have been found and loaded by UCanAccess. All will work fine, but it's better to repa
ir your database.
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Izkaznice;Index=2), making read-only
WARNING:Error in the metadata of the table IzkazniceA: table's row count in the metadata is 23447 but 23458 records have been found and loaded by UCanAccess. All will work fine, but it's better to rep
air your database.
WARNING:Error in the metadata of the table Izpiti: table's row count in the metadata is 21441 but 21451 records have been found and loaded by UCanAccess. All will work fine, but it's better to repair
your database.
WARNING:Error in the metadata of the table Osebe: table's row count in the metadata is 9878 but 9898 records have been found and loaded by UCanAccess. All will work fine, but it's better to repair you
r database.
WARNING:Error in the metadata of the table OsebeArhiv: table's row count in the metadata is 12096 but 12102 records have been found and loaded by UCanAccess. All will work fine, but it's better to rep
air your database.
WARNING:Error in the metadata of the table Potrdila: table's row count in the metadata is 20212 but 20228 records have been found and loaded by UCanAccess. All will work fine, but it's better to repai
r your database.
WARNING:Error in the metadata of the table Zaposlitve: table's row count in the metadata is 20205 but 20212 records have been found and loaded by UCanAccess. All will work fine, but it's better to rep
air your database.
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Firme;Index=0), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Izkaznice;Index=2), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Firme;Index=0), making read-only
WARN  unsupported collating sort order SortOrder[1060(0)] for text index (Db=evidenca_2004.mdb;Table=Izkaznice;Index=2), making read-only
      Obtaining table structure for PUBLIC.Firme
      Obtaining table structure for PUBLIC.FirmeA
...
...

**Comment by chalkos** [comment]
Can you try to repair or migrate the file to the latest MS Access version?

The file seems to be partially corrupted and maybe access can recover it or using access to convert the file to the newest access file format may fix the problem.

**Comment by BorisDomajnko** [comment]
I can export evidenca_2004.mdb to siard without "WARN unsupported collating sort order".
The problem occurs only when it is included.

**Comment by BorisDomajnko** [comment]
Sorry, ignore my previous comment. I have evidenca_2004.mdb and evidenca 2008.mdb. One is ok, one is not!

**Comment by chalkos** [comment]
So I'm a little confused now... To clarify things, please test the following:

1. evidenca_2004.mdb by itself can be exported to SIARD without the warning
2. evidenca_2008.mdb by itself can be exported to SIARD without the warning 
3. converting Izkaznice_IV_MNZ.mdb that includes evidenca_2004.mdb produces the warning
4. converting Izkaznice_IV_MNZ.mdb that includes evidenca_2008.mdb produces the warning
5. converting Izkaznice_IV_MNZ.mdb without including any file produces the warning

and tell me which ones are correct and for the incorrect ones, please provide the correct description.

**Comment by BorisDomajnko** [comment]
-evidenca_2004.mdb by itself can be exported to SIARD with the warning!
-evidenca_2008.mdb by itself can be exported to SIARD without the warning
-converting Izkaznice_IV_MNZ.mdb that includes evidenca_2004.mdb and evidenca_2008.mdb produces the warning for evidenca_2004.mdb

This is the data from the producer and badly supported. Is this warning important? If all the tables get into the siard SIP, then it is up to the viewer to take care about the sorting?

**Comment by chalkos** [comment]
I'm not worried about the sorting. The warning may be a signal that something may be wrong (corrupted?), not necessarily the sorting part.

The warning that we should be focusing on is the one line `table's row count in the metadata is X but Y records have been found and loaded by UCanAccess. All will work fine, but it's better to repair your database.`

Sometimes DBPTK is finding more records, but sometimes it finds less.
Could you try opening the database in access and compare the number of records reported by access with these ones:

* Table: `Izkaznice`, metadata says 11279 but 11303 records have been found.
* Table: `IzkazniceA`, metadata says 23447 but 23458 records have been found.
* Table: `Izpiti`, metadata says 21441 but 21451 records have been found
* Table: `Osebe`, metadata says 9878 but 9898 records have been found
* Table: `OsebeArhiv`, metadata says 12096 but 12102 records have been found.
* Table: `Potrdila`, metadata says 20212 but 20228 records have been found.
* Table: `Zaposlitve`, metadata says 20205 but 20212 records have been found.

**Comment by BorisDomajnko** [comment]
It seems that the evidenca_2008.mdb holsd current values and evidenca_2004.mdb holds some  very old "archive" values that are explicitely addressed by the application, and some tables are even ignored (e.g. 2004 Osebe) by the main application in the main mdb file..

Number of lines for these two mdbs:

table___________ evidenca_2004.mdb____evidenca_2008.mdb_____________PostgreSQL (via DBPTK)
Izkaznice:            23458                           11303                                          11303
IzkazniceA:
Izpiti:                  18026                            21451                                          not checked
Osebe:                12102                            9898                                            not checked
OsebeArhiv:
Potrdila:             59221                             20228                                          not checked
Zaposlitve:                                                20212                                          20212

**Comment by chalkos** [comment]
If you convert to SIARD2 and then to PostgreSQL, can you identify any data loss by looking at the original Access database and at the generated PostgreSQL one?

**Comment by chalkos** [comment]
And is this a pilot blocker issue?

**Comment by BorisDomajnko** [comment]
No. The include links (table<->mdb file) are done per table. I believe that the unused tables may be ignored.
Unfortunately the latest Access does not allow me to fix the original MDB file to minimize some warnings, maybe I need to find some older version.

**Comment by chalkos** [comment]
Maybe an access version between the one used to create the file and the latest has the functionality to upgrade the file. But I'm not experienced with Access.

**Comment by BorisDomajnko** [comment]
I will have a meeting with the producer, maybe they will be willing to do it in the original environment. Or they will not want to touch the obsolete application (mdb). Real life ingests usualy have such problems :(

**Comment by BorisDomajnko** [comment]
The producer decided that they will not touch (repair) the original mdb files in order to keep the integrity. They want to deliver the records in the same state as it was frozen when the app was last shut down years ago (and poorly maintained??).

**Comment by chalkos** [comment]
Unfortunately there is nothing DBPTK can do about corrupted databases, except try to migrate as much data as possible and warn that something might have been lost (which it already does).

The producer might decide to submit multiple representations. In that case they could submit 2 or 3 representations:

1. the original mdb files
2. (optionally) the mdb files after being repaired by Access
3. the SIARD created by DBPTK from the repaired mdb

Does the producer agree with this?

If the producer refuses to provide an uncorrupted database there is nothing DBPTK can do. Even if DBPTK tried to do something about it, it would probably be trying to repair the database (this might be incredibly difficult or even impossible, not only for technical reasons but also in terms of intelectual rights to include Microsoft Access software in DBPTK). Even if DBPTK repairs the database, it would possibly go against the producer's will, so it is not desirable.

**Comment by BorisDomajnko** [comment]
I agree. During ingest we will have to (manually) analyse the data and compare the original and repaired mdb. I hope we will find out that the number of records will be the same.

**Comment by chalkos** [comment]
Are you planning on repairing the database yourself and checking if the problem still happens and if the contents are correct?

Or should I just treat this as solved and close the issue?

**Comment by BorisDomajnko** [comment]
You can close it. The technical comparison will be done as part of manual ingest activities.
