### ISSUE TITLE
SIARDDK Handling of missing primary keys

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#241]
If some tables in a database for some reason have no primary keys, the export to SIARDDK stops with fatal error.

In SIARDDK primary keys are mandatory.

DBPTK should handle this by not killing the export and instead create dummy primary keys in tableIndex for the relevant tables, and present the user with an warning.

**Comment by PhillipTommerholt** [comment]
This could be a pilot blocker. I am awaiting answer from the pilot site and the DNA archivist whether the specific tables with no keys will have to go into the SIP. So @andreaskring if you have more urgent issues I would take these first. But it would be a nice fix, so it's up to you.

**Comment by chalkos** [comment]
@PhillipTommerholt if I may weight in on this, I don't think having the application create dummy primary keys is a good idea. This strategy is prone to choosing the wrong fields and that may have repercussions later on.

I would suggest that the SIARD-DK export module fatally fails sooner (as soon as the database metadata is handed to the export module) when there are tables without a primary key. This way the user is alerted to the fact that SIARD-DK does not support tables without a primary key and they can decide to exclude the table, make a primary key with existing columns or even add a new column to be the primary key. This kind of decision making, in my opinion, is best left to humans.

**Comment by PhillipTommerholt** [comment]
You are more than welcome to join in.
I agree that it should stop or warn sooner in the process.
But from my point of view I would like it to be the choice of the (human) SIP creator if he/she will make the necessary amendments to the original live database, or the SIP package itself. This is both in order to respect that we as an archive can't say how the institutions's systems should look like (we only decide how it looks like when it is represented as a SIP) an in order to use the tool as a "quick copy and quick out" operation with minimum restain on the daily operations. 

The SIARD2.0 format is from my point of view a wider and more flexible format with more optional elements than SIARDDK. Therefore it makes sense to make the SIARD2.0 export module more 1-to-1 with the format. But in SIARDDK for example, each and every column and table needs to have a description, explaining how data within the table or column should be understood/interpreted. This description is possible to store in the DMBSs but very few (nearly noone) use it, and so one still has to work on the SIP product that DBPTK creates, since these descriptions have to be added.

**Comment by chalkos** [comment]
Ok. Seems fair.
When you have information regarding this being (or not) a pilot blocker, tell me so I can adjust the issue labels.

**Comment by PhillipTommerholt** [comment]
:+1:

**Comment by andreaskring** [comment]
@PhillipTommerholt The feature that @chalkos is talking about is already implemented... let's have a quick talk about this. I will contact you.

**Comment by andreaskring** [comment]
@PhillipTommerholt The feature is implemented in [this](https://drive.google.com/file/d/0B8hAEqjI-ScYVE9UUWFxN3loTEU/view?usp=sharing) jar. Could you please check if it is working as expected?

**Comment by PhillipTommerholt** [comment]
I am now getting another fatal error on the export from the specific database, so I haven't seen the warning and the tableIndex.xml yet.

**Comment by andreaskring** [comment]
@PhillipTommerholt Ok, what is the error?

**Comment by PhillipTommerholt** [comment]
> @PhillipTommerholt Ok, what is the error?

I just created it as an issue:
https://github.com/keeps/db-preservation-toolkit/issues/242

**Comment by PhillipTommerholt** [comment]
This is fixed :+1:
