### ISSUE TITLE
SIARDDK: Schemas without tables causes fatal error

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#242]
I have a pilot database, where there are schemas with no tables.
This causes the export to throw a fatal error when creating tableIndex.xml. 

I know that SIARD2.0 handles this situation by throwing a warning and a list of the table-less schemas. Since schemas are not preserved in SIARDKDK the SIARDDK-module doesn't need to throw this warning, but if it is easier to use the code from SIARD2.0 it wouldn't harm if it is handled with such a warning.

**Comment by andreaskring** [comment]
@PhillipTommerholt For some reason I decided to throw a ModuleExecption, which stops the process, in case of schemas with no tables. I will change this.

**Comment by andreaskring** [comment]
The issue have been fixed in [this](https://drive.google.com/file/d/0B8hAEqjI-ScYMjA0SnhoZ1hiRlE/view?usp=sharing) jar. @PhillipTommerholt Could you please check it out?

**Comment by PhillipTommerholt** [comment]
This is fixed :+1:

**Comment by chalkos** [comment]
@andreaskring please create a pull request to include these fixes into the master branch.
