### ISSUE TITLE
Date vs timestamp

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#243]
Applications mostly use date as date without times. In databases we have different date and time datatypes and some even have to deal with time zones.
If the source database uses simple date type or the time is never set  (i.e. is masked by app) in such a column (e.g. date with MS Access) dbptk could use DATE as target format. The main benefit would be nicer output (e.g. 2016-08-04 vs. 2016-08-04 00:00:00) when viewing a table content.

**Comment by chalkos** [comment]
> If the source database uses simple date type ... dbptk could use DATE

agreed.

> or the time is never set (i.e. is masked by app) ... dbptk could use DATE

There is no way for DBPTK to know what the app does, so there is no way for it to know if the app masks the time part.

Since I know from our emails that this is a postgreSQL related issue, I will mark it as such.

**Comment by BorisDomajnko** [comment]
With MS Access you can enter either 4.5.2010 or 4.5.2010 08:20 so DBPTK will have to show 4.5.2010 00:00:00 and 4.5.2010 08:20:20 as this is the same column. Maybe in the future we will have a DBPTK configuration file (i.e. to enforce a mask on a certain column) if more ideas will come up.

**Comment by chalkos** [comment]
A mask would be something related to the presentation of these values, not their extraction.
They should be extracted as provided by the DBMS. Then, when displaying them, the mask could be used.

Since data visualization is not part of DBPTK, I will close this issue.
