### ISSUE TITLE
Move temporary LOB files when possible

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#247]
Move temporary LOB files when possible which is much faster than doing a stream copy.

This applies to SIARD2 with external LOBs.

**Comment by chalkos** [comment]
@andreaskring does SIARD-DK save each LOB in its own file? If it does, it can also benefit from moving files from the temporary folder instead of copying them as streams.

**Comment by andreaskring** [comment]
@chalkos  In SIARDDK, the content of a BLOB is fetched via the `createInputStream()` method from the BinaryCell class and written directly as a single file to the correct location within the SIARDDK folder - see [this](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-core/src/main/java/com/databasepreservation/modules/siard/out/content/SIARDDKContentExportStrategy.java#L345). At the time being CLOBs are always saved as saved as string.

**Comment by andreaskring** [comment]
@chalkos Ok - I understand what you are saying now. We can implement this (either method is ok with me). Currently, I have other tasks that needs priority though, but when there will be more time it is fine with me.

**Comment by chalkos** [comment]
Ok. When I'm done with more urgent issues I'll try to implement this in a way that does not require a lot of modifications in the SIARD modules, so I'll probably change 1 or 2 lines in SIARD-DK to support this enhancement and save you a few minutes 😉

**Comment by andreaskring** [comment]
@chalkos Great - thanks a lot :)

**Comment by andreaskring** [comment]
@chalkos By the way... there may be a challenge implementing this for SIARDDK. In SIARDDK it is mandatory to calculate the md5sum of all files and the current code handles this by putting the LOBs streams through a wrapper as seen [here](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-core/src/main/java/com/databasepreservation/modules/siard/out/metadata/FileIndexFileStrategy.java#L138) (called from [here](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-core/src/main/java/com/databasepreservation/modules/siard/out/content/SIARDDKContentExportStrategy.java#L345)).

**Comment by chalkos** [comment]
No worries there. SIARD-DK could receive the blob `OutputStream` directly from the DBMS and wrap the `DigestOutputStream` around that one instead of around a stream that comes from a file.

**Comment by chalkos** [comment]
What I describe in my previous comment is already implemented in #245. I plan to merge that soon.
