### ISSUE TITLE
SIARDDK: fileIndex.xml only encorporates tables from first schema

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#254]
I am using SNAPSHOT_fixIssue244.
I have a database with tables in several schemas.
There are 27 tables in the first schema and 80 tables in total.
tableIndex.xml is perfect and 80 tables are also exported.
It is only fileIndex.xml that is incomplete. 

I guess this has something to do when tables in several schemas was fixed, but we missed to also handle it correctly in fileIndex.xml.

This is not a pilotblocker since I have a tool to create fileIndex.xml but it is a bug that should be fixed when there is time.

**Comment by andreaskring** [comment]
@PhillipTommerholt Fixed in #261 . Could you please check, if it is working ok in your end?

**Comment by PhillipTommerholt** [comment]
This has been fixed.
