### ISSUE TITLE
SIARDDK: wrong table namespaces when database has several schemas

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#256]
I am using SNAPSHOT_fixIssue244.
I have a database with tables in several schemas.
After successful export the namespaces for the different tables are wrong. 
For example table4.xml has a namespace stating that this is table1.xml.

I guess it is related to #254 and this is a pilot blocker.

**Comment by chalkos** [comment]
@PhillipTommerholt is this a pilot blocker?

**Comment by PhillipTommerholt** [comment]
Yes.

**Comment by andreaskring** [comment]
@PhillipTommerholt Fixed in #261 . Could you please check, if it is working ok in your end?

**Comment by PhillipTommerholt** [comment]
This has been fixed.
