### ISSUE TITLE
SIARDDK: documents/document folders not assigned unique numbers

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#259]
This is a pilot blocker.

I have a database with LOBs where DBPTK exports succesfully.
The end product, however, does not conform to "bek. 1007".

DBPTK assigns documents unique IDs within the different docCollections (starting from ID=1). 
IDs must be unique within the whole SIP package.

**Comment by andreaskring** [comment]
@PhillipTommerholt Fixed in #261 . Could you please check, if it is working ok in your end?

**Comment by PhillipTommerholt** [comment]
I have a 5-8hour export running.
So far I can see that documents in the different docCollections are Unique :+1: 

But I have to wait to the export finishes in order to find the tables and see if docID's also are correct there. So if the export succeeds I can give a final answer on monday.

**Comment by PhillipTommerholt** [comment]
This has been fixed.
