### ISSUE TITLE
Change the name of the button from "apply" to "save"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-preservation-toolkit#267]
![screen shot 2016-09-27 at 21 56 27](https://cloud.githubusercontent.com/assets/3181302/18891500/64333956-84fd-11e6-8e1d-5ce7bf6efcc1.png)

**Comment by jmaferreira** [comment]
Sorry.. this is a viewer issue.. move it please.

**Comment by chalkos** [comment]
moved... https://github.com/keeps/db-visualization-toolkit/issues/66
