### ISSUE TITLE
jdbc and filemaker

### ISSUE THREAD

**Issue by atomotic** [keeps/db-preservation-toolkit#270]
i'm trying to convert a filemaker database (using jdbc)

```
java -cp '*' com.databasepreservation.Main \
	--import=jdbc --import-driver=com.filemaker.jdbc.Driver \
    --import-connection="jdbc:filemaker://localhost/asfe?user=Admin" \
    -e siard-1 -ef asfe.siard
```

the connection works, but i got this error:
```
2016-10-06 15:17:02,284 [main] ERROR (c.d.Main) Fatal error while converting the database (Error while exporting structure: dbname cannot be blank)
```
attached: [dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/513801/dbptk-app.log.txt)

maybe is something not supported by filemaker jdbc?
the last chapter of this guide describe the supported standards: https://www.filemaker.com/support/product/docs/11/fms/fm11_odbc_jdbc_guide_en.pdf

**Comment by chalkos** [comment]
This is actually to avoid creating invalid SIARD files. it seems like the JDBC module is not being able to get the database name, and the SIARD file must always have a database name. So when it is not there, the whole thing is aborted to avoid wasting time creating something that would be invalid from this very early stage.

I think the solution for this might involve the creation of a filemaker-specific import module.

**Comment by atomotic** [comment]
ok, thanks! i will try in my spare time to make a plugin, it's not on my priority list right now.

**Comment by brianmatthewthomas** [comment]
I just tried working with a Filemaker database (I have 77 total) and got the same error then noticed this ticket. I was wondering if there was any movement on making a plug-in for this situation? I am by no means a programmer so I do not know how much help I could be with this, but I don't want to try re-inventing the wheel or giving up if someone has already got a solution.

**Comment by luis100** [comment]
@brianmatthewthomas there was no movement on this front since this ticket as no one has step forward to develop or to fund the development of a plugin/module that would provide support for Filemaker databases.
If you which to develop or to fund the development of this module please contact us (myself or @chalkos ).

**Comment by brianmatthewthomas** [comment]
Ok. I doubt at this point we would be sponsoring a module, although I will ask internally just in case. I will post to this thread and contact you or @chalkos if we do decide to move forward. Thank you for the information and quick response.
