### ISSUE TITLE
Reverse transformation fails

### ISSUE THREAD

**Issue by zhuozhih** [keeps/db-preservation-toolkit#275]
Description: 
Hi I made a simple database in mysql and then exported it into the siard-2 format. But when I tried to convert the siard file back to a mysql database, I kept receiving the following message:
"ERROR Unrecognized option: addresses.siard"

I've double checked my working directory and file names. I don't know where lies the problem. Can you take a look? 

Steps required to reproduce the bug:

1. Convert the mysql database "addresses" into file "addresses.siard". The log is attached below. 

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/545538/dbptk-app.log.txt)

$ java -jar dbptk-app-2.0.0-beta5.jar --import mysql --import-hostname=localhost --import-database="addresses" --import-username=root --import-password="some_password" --export siard-2 --export-file=addresses.siard

2. I used the following command to try to convert the siard file back to the original mysql format. 

$ java -jar dbptk-app-2.0.0-beta5.jar --import siard-2 --import-file= "addresses.siard" --export mysql --export-hostname = localhost --export-database = “another_address_db” --export-username = root --export-password = "some_password"

Attach the dbptk-app.log.txt file below.

**Comment by chalkos** [comment]
It seems like you have some extra spaces in the command that confusing the application

Try this:

`$ java -jar dbptk-app-2.0.0-beta5.jar --import=siard-2 --import-file=addresses.siard --export=mysql --export-hostname=localhost --export-database=another_address_db --export-username=root --export-password="some_password"`

**Comment by zhuozhih** [comment]
It worked! Thanks a lot.

**Comment by chalkos** [comment]
No problem ;)
