### ISSUE TITLE
Stored procedures source code is not being imported from MySQL (sakila DB)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-preservation-toolkit#277]
Description: 

Stored procedures source code is not being imported from MySQL (sakila DB)

Steps required to reproduce the bug:

1.  Extract Sakila from MySQL to SIARD 2
2.  Load into the DB viewer
3.  The names of Stored procedures are there, but there is no code. After inspecting the SIARD. Its not there either.

**Comment by chalkos** [comment]
Fixed in https://github.com/keeps/db-preservation-toolkit/commit/7f431bb56acc55d56302ac703a93e57672069dd0
