### ISSUE TITLE
In the viewer, how to I distinguish between a stored procedure and a function?

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-preservation-toolkit#278]
They appear in the same page... and look exactly the same!

![screen shot 2016-11-06 at 11 15 27](https://cloud.githubusercontent.com/assets/3181302/20037145/618a4e0e-a412-11e6-84d1-c988689d7dc5.png)

**Comment by chalkos** [comment]
This issue was moved to keeps/db-visualization-toolkit#75
