### ISSUE TITLE
PostgreSQL: creating siard with binary data

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#283]
This worked with --export-external-lobs, but error without this option:

```
d:\projekti\E-ARK>java -Xmx1000m -Dfile.encoding=UTF-8 -jar dbptk-app-2.0.0-beta6.jar -i postgresql -ih pluton -idb testB -iu pg_boris -ip x -ide -ipn 5432 -e siard-2 -ef out_pgB1.siard
      Converting database: postgresql to siard-2
      Initializing target database
      Converting database structure
      Obtaining table structure for drivers.persons
      Database structure converted
      Getting contents from table 'drivers.persons'
      Total of 3 row(s) processed
      Obtained contents from table 'drivers.persons'
WARN  Schema public was not exported because it does not contain tables.
      Run time 0m 0s
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at d:\projekti\E-ARK\dbptk-report-20161122161344655.txt
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
Exception in thread "Thread-2" Exception in thread "Thread-0" java.lang.IllegalStateException: A PathInputStreamProvider was cleaned by a shutdown hook. Path: C:\Users\BDOMAJ~1\AppData\Local\Temp\dbptk5719866057554244460lob. Source: java.lang.Thread.getStackTrace(Unknown Source)
com.databasepreservation.common.PathInputStreamProvider.<init>(PathInputStreamProvider.java:72)
com.databasepreservation.model.data.BinaryCell.<init>(BinaryCell.java:53)
com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.rawToCellSimpleTypeBinary(PostgreSQLJDBCImportModule.java:417)
com.databasepreservation.modules.jdbc.in.JDBCImportModule.convertRawToCell(JDBCImportModule.java:1206)
com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.convertRawToRow(PostgreSQLJDBCImportModule.java:250)
com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1509)
com.databasepreservation.Main.run(Main.java:131)
com.databasepreservation.Main.internal_main(Main.java:84)
com.databasepreservation.Main.main(Main.java:62)

        at com.databasepreservation.common.PathInputStreamProvider$1.run(PathInputStreamProvider.java:83)
Exception in thread "Thread-1" java.lang.IllegalStateException: A PathInputStreamProvider was cleaned by a shutdown hook. Path: C:\Users\BDOMAJ~1\AppData\Local\Temp\dbptk6732205389483065495lob. Source: java.lang.Thread.getStackTrace(Unknown Source)
com.databasepreservation.common.PathInputStreamProvider.<init>(PathInputStreamProvider.java:72)
com.databasepreservation.model.data.BinaryCell.<init>(BinaryCell.java:53)
com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.rawToCellSimpleTypeBinary(PostgreSQLJDBCImportModule.java:417)
com.databasepreservation.modules.jdbc.in.JDBCImportModule.convertRawToCell(JDBCImportModule.java:1206)
com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.convertRawToRow(PostgreSQLJDBCImportModule.java:250)
com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1509)
com.databasepreservation.Main.run(Main.java:131)
com.databasepreservation.Main.internal_main(Main.java:84)
com.databasepreservation.Main.main(Main.java:62)

        at com.databasepreservation.common.PathInputStreamProvider$1.run(PathInputStreamProvider.java:83)
java.lang.IllegalStateException: A PathInputStreamProvider was cleaned by a shutdown hook. Path: C:\Users\BDOMAJ~1\AppData\Local\Temp\dbptk2567323079671428920lob. Source: java.lang.Thread.getStackTrace(Unknown Source)
com.databasepreservation.common.PathInputStreamProvider.<init>(PathInputStreamProvider.java:72)
com.databasepreservation.model.data.BinaryCell.<init>(BinaryCell.java:53)
com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.rawToCellSimpleTypeBinary(PostgreSQLJDBCImportModule.java:417)
com.databasepreservation.modules.jdbc.in.JDBCImportModule.convertRawToCell(JDBCImportModule.java:1206)
com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.convertRawToRow(PostgreSQLJDBCImportModule.java:250)
com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1509)
com.databasepreservation.Main.run(Main.java:131)
com.databasepreservation.Main.internal_main(Main.java:84)
com.databasepreservation.Main.main(Main.java:62)

        at com.databasepreservation.common.PathInputStreamProvider$1.run(PathInputStreamProvider.java:83)
```

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/606733/dbptk-app.log.txt)

**Comment by chalkos** [comment]
This happens because the way binary files are handled was changed a lot in the last beta.

And to make sure they were handled correctly I implemented some safeguards. These safeguards should not execute normally, but are executed when needed. When the safeguards execute, they print out these awful messages so that people feel compelled to reporting them :)

These messages should tell me enough to fix the problem. Thanks for reporting it.

**Comment by chalkos** [comment]
Try with this version [dbptk-app-2.0.0-SNAPSHOT-283-1.zip](https://github.com/keeps/db-preservation-toolkit/files/607120/dbptk-app-2.0.0-SNAPSHOT-283-1.zip)

**Comment by BorisDomajnko** [comment]
It seems OK now:

d:\projekti\E-ARK>java -Xmx1000m -Dfile.encoding=UTF-8 -jar dbptk-app-2.0.0-SNAPSHOT-283-1.jar -i postgresql -ih pluton -idb testB -iu pg_boris -ip x -ide -ipn 5432 -e siard-2 -ef out_pgB1.siard
      Converting database: postgresql to siard-2
      Initializing target database
      Converting database structure
      Obtaining table structure for drivers.persons
      Database structure converted
      Getting contents from table 'drivers.persons'
      Total of 3 row(s) processed
      Obtained contents from table 'drivers.persons'
WARN  Schema public was not exported because it does not contain tables.
      Run time 0m 0s
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at d:\projekti\E-ARK\dbptk-report-20161125081743715.txt
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

d:\projekti\E-ARK>java -Xmx1000m -Dfile.encoding=UTF-8  -jar  dbptk-app-2.0.0-SNAPSHOT-283-1.jar -e postgresql -eh 10.0.92.38 -edb eark_testB1 -eu pg_eark -ep x -ede -epn 5432 -i siard-2 -if out_pgB1.siard
      Converting database: siard-2 to postgresql
      Target database does not exist. Creating database eark_testB1
      Exporting database structure
      Exporting schema structure for schema drivers
      Exporting table structure for persons
      Exporting schema structure for schema drivers
      Exporting database structure finished
      Obtaining contents from table 'drivers.persons'
      Exporting content to table for drivers.persons
      Total of 4 row(s) processed
      Obtained contents from table 'drivers.persons'
      Adding foreign keys for table drivers.persons
      Finished adding foreign keys
      Run time 0m 1s
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at d:\projekti\E-ARK\dbptk-report-20161125082504710.txt
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

d:\projekti\E-ARK>
