### ISSUE TITLE
Row index number mismatch

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#284]
Description: When I did an export to SIARD2 from postgresql and looked at the lob files then why is the row number in the filename record358.txt different from the row number in the table of database which is 354? Screenshot attached. (by @Laurira)

Steps required to reproduce the bug:

1. Convert a specific postgresql db to siard2
2. the original database, on a postgres db management GUI software, shows a row index of 354 for a row that contains a LOB; but in the SIARD the LOB is saved as `record358.txt`.

The log was sent to email and does not provide any useful info.

I have the SIARD file on my email (subject: "dbptk errors" from Lauri Rätsep)

**Comment by chalkos** [comment]
We have already discussed this to some extent by email, but since I could not find any missing/wrong data on my end, I have a few questions:

1. can you find anything wrong/missing? besides the strange index number thingy
2. there should be 3 or 4 records more in the SIARD than in the DB, does this happen?
3. is this blocking an E-ARK pilot?

**Comment by Laurira** [comment]
1. I do not find anything wrong or missing besides the index number issue.
2. There are exactly the same amount of records as there were in the database.
3. This is not blocking the pilot.

**Comment by chalkos** [comment]
From previously exchanged emails with @Laurira it seems that this is not happening anymore.
Can you test with version 2.0.1?

**Comment by Laurira** [comment]
I tried with v2.0.1, works nicely, no problems detected.

**Comment by chalkos** [comment]
Ok, thanks
