### ISSUE TITLE
bin files disappear after restore (when --export-external-lobs)

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#285]
1. I created a SIARD2 package using the --export-external-lobs option. At the end this message is displayed:
      _Run time 0m 0s
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at d:\projekti\E-ARK\dbptk-report-20161125083353195.txt
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new_
I suggest we add a text like
      The exported LOBs are located in at d:\projekti\E-ARK\out_pgB.siard_lobseg_1\ 

2. Then I created a database from this package. After this i have noticed that the recordN.bin files disappeared from d:\projekti\E-ARK\out_pgB.siard_lobseg_1\content\schema1\table1\lob3\
Is this a bug or a feature? It is not mentioned in -h output or instructions https://www.database-preservation.com/

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/612723/dbptk-app.log.txt)

------------------------

### Tasklist (by @chalkos):

- [ ] Log which folders were created outside the SIARD (e.g. out_pgB.siard_lobseg_1) after the conversion
- [x] do not delete LOBs when importing from a SIARD 2 w/ external LOBs.

**Comment by chalkos** [comment]
**1)** Why? It is part of the SIARD format and other parts of the SIARD format are not being detailed like that.

**2)** That is a very, very bad bug. Thanks for finding it!

**Comment by BorisDomajnko** [comment]
1) The tool might be used only occasionaly or only once by some users, they might fall into a trap by not being familiar with the tool. But if it is documented at some other place then it is ok.

**Comment by chalkos** [comment]
1. I understand your concern. But the LOBs only get created outside the SIARD if the user uses a specific parameter:

`-eel, --export-external-lobs    (optional) Saves any LOBs outside the siard file.`

The tool does not trap the user. It is the user that decides the behaviour of the tool, and must stick with that decision when handling the created SIARD file (and external LOB files).

The actual documentation (regarding external LOBs) should be officially released in a few weeks.

**Comment by BorisDomajnko** [comment]
1. ok. I was concerned because the name was not specified by the user (e.g. out_pgB.siard_lobseg_1). In the documentation you could state that the external LOBs will be created in the same folder as the created SIARD file (which can be defined by -ef option).

**Comment by chalkos** [comment]
1. Ok. I guess there is no harm in adding that information after the conversion.
