### ISSUE TITLE
Using -ede still tries to use encryption in postgresql export module

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#286]
I exported Sakila database from Mysql to SIARD (file1)
Then I exported it to Postgresql.
Then I exported Sakile from Postgresql to SIARD (file2).

In the last export I got errors
 “Connection error while importing/exporting” “… The server does not support SSL.”
I tried with and without “-ede” flag.

Log dbptk-app.log.txt](https://github.com/keeps/db-visualization-toolkit/files/613142/dbptk-app.log.txt)

But it created SIARD file so this is not critical

**Comment by chalkos** [comment]
I converted a SIARD file to Postgres using DBPTK 2.0.1 and this did not happen.

Command and output, first without `-ede` and then added it.
I used a Postgres without configuring support for encryption (it was docker postgres 9.4 without modifications)

```
java -jar dbptk-app-2.0.1.jar -i siard-2 -if baasTestfis.siard.zip -e postgresql -eh localhost -edb postgres -eu postgres -ep 123456      
      Converting database: siard-2 to postgresql
      Initializing database
ERROR Fatal error while converting the database (SQL error creating connection)
      Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new


java -jar dbptk-app-2.0.1.jar -i siard-2 -if baasTestfis.siard.zip -e postgresql -eh localhost -edb postgres -eu postgres -ep 123456 -ede
      Converting database: siard-2 to postgresql
      Initializing database
      Target database already exists, reusing it.
      Obtained database structure
      Exporting database structure
      ....
```

@Laurira can you confirm that it is working?

**Comment by Laurira** [comment]
I tried the same thing
Database Sakila MySql (localhost) ->SIARD2 ->Postgresql -> SIARD2

The last conversion gives still an error. This -ede error is gone but it creates still an empty SIARD file and log says:

2019-01-28 09:55:29,385 [main] ERROR (c.d.Main) Fatal error: Unexpected exception (null)
java.lang.NullPointerException: null
	at com.databasepreservation.model.modules.filters.ObservableFilter.handleDataCloseSchema(ObservableFilter.java:143)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:1650)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:79)
	at com.databasepreservation.Main.run(Main.java:173)
	at com.databasepreservation.Main.internalMain(Main.java:115)
	at com.databasepreservation.Main.main(Main.java:89)

**Comment by luis100** [comment]
This seems to be an unrelated bug.

Looking into the [code](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-model/src/main/java/com/databasepreservation/model/modules/filters/ObservableFilter.java#L143), there seems to be a unexpected situation (NullPointerException) due to schemas without any table on them.

**Comment by Laurira** [comment]
Which release should I use to test this?

**Comment by chalkos** [comment]
I will be releasing a new version when I close the issues for this milestone. It is probably better if you verify that release instead of verifying one release for each fix.

I'll be closing this since it seems to be fixed. If the same problem resurfaces later on we can re-open the issue.
