### ISSUE TITLE
dbptk-report-...: missing the dbptk tool version 

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#297]
The producer has sent me the output file and the report. However, in the report I cannot see which DBPT tool they have used (and we have just switched form beta6 to beta7). I suggest to modify the header:  Database Preservation Toolkit **(v 2.0.0.beta6)** -- Conversion Report

1. the producer has sent me dbptk-report-20170126124051360.txt
2. this is the header:

Database Preservation Toolkit -- Conversion Report
==================================================

## Parameters
**Import module:** oracle
- server name = 10.32.2.40
- database = test.gurs.sigov.si
- username = rpe
- password = <filtered>
- port number = 1523

**Export module:** siard-2
- file = D:\arhiv_test\outRPEtest.siard
- compress = false
- pretty xml = false
- table filter = D:\arhiv_test\spisek_tabel_rpe01.txt

Date: 2017-01-26
3. The producer has not sent us (the archive) the log

Attach the dbptk-app.log.txt file below.
-

**Comment by chalkos** [comment]
The report file has been modified to include the header you suggested (with the version).

Versions 2.0.0-beta6 and 2.0.0-beta7.1 do not show the version.
Starting with version 2.0.0-beta7.2, the version is included in the report file.
