### ISSUE TITLE
Pilot error: transfer from oracle to PostgreSQL

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#298]
The pilot producer has created a siard with 118 tables. Errors occur if I want to transfer it to PostgreSQL. 

1. Get the siard file from the producer, containing content of a large register
2. 
java -Xmx1000m -Dfile.encoding=UTF-8  -jar  dbptk-app-2.0.0-beta7.1.jar -e postgresql -eh 10.0.92.38 -edb eark_gurs_RPE -eu pg_eark -ep ... -ede -epn 5432 -i siard-2 -if “S:\PROJEKTI_ARS\e-ARH.si\E-ARK\Izvajanje projekta\TestiranjeOrodij\databases\GURS_SiardIzvoz\outRPEtest.siard”

3. 

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/734765/dbptk-app.log.txt)

**Comment by BorisDomajnko** [comment]
According to the producer the table does not have duplicate columns.
The structure:
[rpe-ul.txt](https://github.com/keeps/db-preservation-toolkit/files/735428/rpe-ul.txt)

**Comment by chalkos** [comment]
I have done some testing on this and I could not find the cause.

Could you provide me with the metadata.xml?
(if it is not publicly available, you can send it to my KEEPS email)

**Comment by BorisDomajnko** [comment]
metadata.xml extracted and sent by email...
