### ISSUE TITLE
Timestamps get shifted around daylight saving time change

### ISSUE THREAD

**Issue by ateras** [keeps/db-preservation-toolkit#299]
I'm trying to convert a database containing meteorological observations from MySQL to SIARD. The data includes time stamps stored in columns of the type "datetime". The timestamps get shifted by one hour during the hours when moving to daylight savings time.

Here's a simplified table with values allowing to reproduce the issue. Our time zone at the moment when doing the testing is EET (UTC+2). Depending on your time zone, it may be necessary to change the times in the example by a few hours to reproduce the behaviour.

Create a table with some values (also attached as [timetest.sql.txt](https://github.com/keeps/db-preservation-toolkit/files/735016/timetest.sql.txt)):
```
DROP TABLE IF EXISTS timetest;
CREATE TABLE timetest (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  samptime datetime NOT NULL,
  temperature float DEFAULT NULL
);

INSERT INTO timetest (samptime, temperature) VALUES 
('2015-03-29 02:50:00', '2.5'), 
('2015-03-29 03:10:00', '3.5'), 
('2015-03-29 03:30:00', '4.5'), 
('2015-03-29 03:50:00', '5.5'), 
('2015-03-29 04:10:00', '6.5');
```

Read the file above into the empty database siard_test:
`mysql -u test --password=xxx siard_test <timetest.sql`

Export the database from MySQL into SIARD:
`java -jar ~/Downloads/siard/dbptk-app-2.0.0-beta7.1.jar --import mysql --import-hostname=localhost --import-database="siard_test" --import-username=test --import-password=xxx --export siard-2 --export-file=siard_test.siard2`

Import the database back from SIARD into a new database in MySQL:
`java -jar ~/Downloads/siard/dbptk-app-2.0.0-beta7.1.jar --import=siard-2 --import-file=siard_test.siard2 --export=mysql --export-hostname=localhost --export-database="siard_import_test" --export-username=test --export-password=xxx`

Show the content of both databases in MySQL (original and the one imported back from SIARD):
```
mysql> \u siard_test
Database changed
mysql> select * from timetest;
+----+---------------------+-------------+
| id | samptime            | temperature |
+----+---------------------+-------------+
|  1 | 2015-03-29 02:50:00 |         2.5 |
|  2 | 2015-03-29 03:10:00 |         3.5 |
|  3 | 2015-03-29 03:30:00 |         4.5 |
|  4 | 2015-03-29 03:50:00 |         5.5 |
|  5 | 2015-03-29 04:10:00 |         6.5 |
+----+---------------------+-------------+
5 rows in set (0.00 sec)
mysql> \u siard_import_test
Database changed
mysql> select * from timetest;
+----+---------------------+-------------+
| id | samptime            | temperature |
+----+---------------------+-------------+
|  1 | 2015-03-29 02:50:00 |         2.5 |
|  2 | 2015-03-29 04:10:00 |         3.5 |
|  3 | 2015-03-29 04:30:00 |         4.5 |
|  4 | 2015-03-29 04:50:00 |         5.5 |
|  5 | 2015-03-29 04:10:00 |         6.5 |
+----+---------------------+-------------+
5 rows in set (0.00 sec)
```

In the SIARD file itself, the rows look like this:
```
<row><c1>1</c1><c2>2015-03-29T00:50:00.000Z</c2><c3>2.5</c3></row>
<row><c1>2</c1><c2>2015-03-29T01:10:00.000Z</c2><c3>3.5</c3></row>
<row><c1>3</c1><c2>2015-03-29T01:30:00.000Z</c2><c3>4.5</c3></row>
<row><c1>4</c1><c2>2015-03-29T01:50:00.000Z</c2><c3>5.5</c3></row>
<row><c1>5</c1><c2>2015-03-29T01:10:00.000Z</c2><c3>6.5</c3></row>
```

The behaviour is identical with both SIARD versions (modules siard-1 and siard-2).

If I export the database with mysqldump into a mysql dump file and read it back, the time stamps stay unchanged. Dump file also attached ([siard_test_dump.sql.txt](https://github.com/keeps/db-preservation-toolkit/files/735239/siard_test_dump.sql.txt)).

**Comment by chalkos** [comment]
This was originally reported in #22, but other priorities appeared and this was left behind.

Thanks for your very elaborate report and instructions on how to reproduce the issue.
I will have a look at this and update this issue.

**Comment by ateras** [comment]
A renewed testing revealed that the problem can be solved by giving the command line parameter "‑Duser.timezone=GMT" at the invocation of the tools. That tells Java not to do any unexpected conversions when handling the timestamp fields.

A simple fix would be to add this information to the documentation of the toolkit.

**Comment by luis100** [comment]
This can now be added to the desktop app quite easily.

**Comment by luis100** [comment]
@hmiguim add to documentation

**Comment by hmiguim** [comment]
Documentation updated.
