### ISSUE TITLE
editing the SIARD file manually

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#304]
Description: 

Steps required to reproduce the bug:
1. unzip the SIARD
2. edit the .\header\metadata.xml
3. zip the folder to the SIARD using no compression
4. Load the SIARD to the dbvtk

Getting the error
ERROR Fatal error while converting the database (File "header/metadata.xsd" is missing in container)

**Comment by PhillipTommerholt** [comment]
What kind of edit did you do in metadata.xml?

**Comment by chalkos** [comment]
The error seems pretty straightforward: `header/metadata.xsd` is not present in the zip file.

Can you confirm this?

**Comment by Laurira** [comment]
Actually I just wanted to know if I can manually edit SIARD files? Even when I do not edit files then the dbvtk do not like my SIARD any more.
I just unzip and zip the SIARD with 7-zip for Windows. I do not use compression or encryption. Should I use some other zip creation tool?

header/metadata.xsd is present in zip file.

**Comment by chalkos** [comment]
Try the following, starting from the SIARD file created by DBPTK:

1. create a backup of the SIARD file
2. open the SIARD file in 7-zip and navigate to the `header` folder
3. drag and drop the new metadata.xml onto 7-zip
4. confirm that you want to replace the file on the zip with the new one

This should allow you to change the `metadata.xml` and maintain all of the original ZIP format settings (compression, mode, etc).

**Comment by Laurira** [comment]
This worked nicely, thanks.
