### ISSUE TITLE
Confirm that the accentuated chars are being exported correctly (or imported correctly) on the viewer from Access files

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-preservation-toolkit#309]
See example "Relações":

![screen shot 2017-03-19 at 14 42 57](https://cloud.githubusercontent.com/assets/3181302/24081811/8f5648e8-0cb2-11e7-930c-e438acebea46.png)

 ```
   <row>
    <c1>PT/AHD/MU/GM/GNP/RRI/0859</c1>
    <c2>Relações internacionais: Organisation de l&apos;Unité Africaine</c2>
    <c3>1971-1974</c3>
    <c4>1971</c4>
    <c5>1974</c5>
    <c6>Série</c6>
    <c7>2 U.I.; papel</c7>
  </row>

```

**Comment by chalkos** [comment]
This is a bug in the database visualization toolkit, I will move the issue.

**Comment by chalkos** [comment]
This issue was moved to keeps/db-visualization-toolkit#104
