### ISSUE TITLE
Add to the examples on database-preservation.com the "-Dfile...=utf-8"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-preservation-toolkit#312]
The app always complains about that. Another issue that the users face is that they always paste the "$" that is on the examples and don't understand why it doesn't work.

**Comment by jmaferreira** [comment]
Remove the "\" from the examples.

**Comment by chalkos** [comment]
- [x] add utf8 to examples
- [x] remove `$` from examples
- [x] remove `\` from examples (and make them all one-liners)
