### ISSUE TITLE
Improve the codebase

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#316]
This issue gathers multiple internal code changes that should be done (so they are not forgotten). The list of wanted changes may grow and comments may be added to individual items.

- [ ] ~Testing: test the conversion of database contents (not just metadata)~
Moved here: #354

- [ ] ~Move the Solr export module to the database visualization toolkit~
Moved here: https://github.com/keeps/db-visualization-toolkit/issues/124

- [ ] ~Improve the datatype export via abstractions.~
- [ ] ~Improve the datatype import. There is an abstraction to import datatypes, but it could be improved to be more flexible and support a wider range of options to handle datatypes at different granularity levels~
  - both of these will be implemented as other areas of the code are improved and a need arises to have more control over the datatype conversions

- [ ] ~Improve the way queries are handled~
  - ~there is a finite number of sequential operations that need to be executed to extract metadata and data from a database. There should be some generic approach to defining them and their order (possibly by allowing "injecting" pre-operation and post-operation actions).~
  - ~this should support the basic workflow (extracting metadata and then extracting the data from schemas/tables/rows/cells)~
  - ~this should support some specific parts (don't extract contents, add foreign keys in the end, modify primary key names)~
Moved here: #356

- [ ] ~Use the observer pattern to report progress~
  - ~use this in the command line UI to output progress~
  - ~all modules should report what is being done~
  - ~change the Reporter to be an observer which (at least) writes information regarding potential data-loss issues (which all observers should be notified about)~
  - ~different kinds of notifications may be sent (like data-loss, progress, etc) and may be handled or ignored by observers~
Moved here: #357

- [ ] ~Improve the documentation (possibly using https://readthedocs.io)~
Moved here: https://github.com/keeps/db-preservation-toolkit/issues/355

- [ ] ~Upgrade to using Java 9 and jigsaw (and make all/some modules separate plugins). otherwise loading a JAR containing a new import/export module will continue to be a tricky process.~
Wontfix: This is too risky to be worth it, and would bring in a different kind of problem, like "running java 11 on windows XP"

**Comment by luis100** [comment]
@chalkos review this list, check the items done, strikeout the ones we wont do, and create issues for the ones we will do next.

**Comment by chalkos** [comment]
done
