### ISSUE TITLE
Support the new SIARD 2.1

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#329]
Tasks:

- [x] add support for importing SIARD 2.1 (at least all the features that are currently supported by SIARD 2.0 import module)

- [x] add support for exporting SIARD 2.1 (at least all the features that are currently supported by SIARD 2.0 export module)

- [x] ensure that SIARD 2.0 is still supported after adding support for SIARD 2.1

**Comment by chalkos** [comment]
@DavidUnderdown you may want to follow this issue, since SIARD 2.1 adds support for some of the procedures in the PRONOM database (#328)

**Comment by DavidUnderdown** [comment]
Thanks

**Comment by DavidUnderdown** [comment]
Any idea when a 2.1 release will be available?

**Comment by chalkos** [comment]
It will be by the end of 2019, in the context of a public tender by the National Archives of Estonia

**Comment by chalkos** [comment]
It will be by the end of 2019

**Comment by jmaferreira** [comment]
Is this development done?

**Comment by chalkos** [comment]
@jmaferreira no

**Comment by chalkos** [comment]
@jmaferreira  You can check the status of the current milestone at https://github.com/keeps/db-preservation-toolkit/projects/2

**Comment by PhillipTommerholt** [comment]
@luis100 

Just a small detail. In the new SIARD2.1 the folder called "header" should now contain a folder named "siardversion" and not "version" as previously. 

My observation is that DBPTK 2.3.0 RC still produces the old folder naming.  
See P_4.2-4 in SIARD 2.1
