### ISSUE TITLE
Erro Microsoft-SQL-Server to SIARD2

### ISSUE THREAD

**Issue by bruno-raposo-dglab** [keeps/db-preservation-toolkit#333]
Description: É realizada a seguinte tarefa, no final nem sequer fez criação do ficheiro "dbptk-app.log".

I:\data_preservation>java  "-Dfile.encoding=UTF-8" -jar dbptk-app-2.0.0.jar -i m
icrosoft-sql-server -ide -is ctestes.tt.pt -idb DigitArq5 -iu sa -ip d1g1t4rq! -
e siard-2 -ef digitar5.siard2
      Converting database: microsoft-sql-server to siard-2
      Initializing target database
      Converting database structure
ERROR Connection error while importing/exporting
ERROR Fatal error while converting the database (SQL error while connecting)
      Disabling connection encryption (for modules that support it) and trying a
gain.
      Converting database: microsoft-sql-server to siard-2
      Initializing target database
      Converting database structure
ERROR Connection error while importing/exporting
ERROR Fatal error while converting the database (SQL error while connecting)
      Troubleshooting information can be found at http://www.database-preservati
on.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-too
lkit/issues/new

Steps required to reproduce the bug:

1. 
2. 
3. 

Attach the dbptk-app.log.txt file below.

**Comment by chalkos** [comment]
O log deverá estar numa pasta dbptk em `I:\data_preservation`, vou precisar do log para diagnosticar o problema.

**Comment by bruno-raposo-dglab** [comment]
Tem razao, encontrava-se lá.

No entanto comecei a fazer outra conversao de Access para SIARD2 e obtive a seguinte informação

I:\data_preservation>java  "-Dfile.encoding=UTF-8" -jar dbptk-app-2.0.0.jar -i m
icrosoft-access -if PIDE_DGS_BASE_OLD.mdb -e siard-2 -ef pide.siard2
      Converting database: microsoft-access to siard-2
      Initializing target database
      Converting database structure
ERROR Connection error while importing/exporting
ERROR Fatal error while converting the database (SQL error while connecting)
      Disabling connection encryption (for modules that support it) and trying a
gain.
      Converting database: microsoft-access to siard-2
      Initializing target database
      Converting database structure
ERROR Connection error while importing/exporting
ERROR Fatal error while converting the database (SQL error while connecting)
      Troubleshooting information can be found at http://www.database-preservati
on.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-too
lkit/issues/new


Haverá algum problema com o .jar???
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/1923620/dbptk-app.log.txt)

**Comment by chalkos** [comment]
No MS SQL Server existem problemas de conexão (a aplicação não consegue conectar ao servidor com os parâmetros que lhe foram dados):

The TCP/IP connection to the host ctestes.tt.pt, port 1433 has failed. Error: "Connection refused: connect. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

----------

No Access, a password está errada:

net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::2.0.0 Password authentication failed.

**Comment by chalkos** [comment]
@bruno-raposo-dglab Este tipo de questões deverá entrar preferencialmente via o nosso sistema de Helpdesk: [helpdesk.keep.pt](helpdesk.keep.pt)
