### ISSUE TITLE
Insufficent privileges to run DBPTK should be responded with proper error message

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#339]
### Problem

At the moment user do not understand that he/she has insufficent privileges to run the DBPTK.

### Solution info

Try to reproduce this kind of error in different DBMSes and show a better message when that happens.

**Comment by luis100** [comment]
Please note that the solution should also cope well with the GUI to be developed at #86

**Comment by Laurira** [comment]
I have a user who should not have access and it responds that almost proper error message
**"ERROR Fatal error while converting the database (ERROR: permission denied for schema fotisn  Position: 22)**

I say "almost" because the schema I tried to reach was "fotis" not "fotisn". Is it some new line character there or what?


PS C:\Users\laurir\Desktop\DBPTK> java "-Dfile.encoding=UTF-8" -jar dbptk-app-2.1.0-BETA.jar -i postgresql --import-hostname=***.***.***.*** -idb fotis -iu lauri -ip ******************** -ipn 5433 -ide -e siard-2 -ef fotisFromPriit.siard
      Converting database: postgresql to siard-2
      Initializing database
      Obtaining table structure for fotis.autor_abi
ERROR Fatal error while converting the database (ERROR: permission denied for schema fotisn  Position: 22)
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at C:\Users\laurir\Desktop\DBPTK\dbptk-report-20190219115812889.txt
      Log files and migration reports were saved in C:\Users\laurir\Desktop\DBPTK
      Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

**Comment by chalkos** [comment]
@Laurira  Please test 2.1.0-BETA with MySQL since it is the only error handling mechanism that is implemented.

Postgres is still using a mix of the old and new error handling method.

**Comment by Laurira** [comment]
Tried with mysql
**User with all grants (but not root user) gets:**
WARN  The selected MySQL user does not have permissions to list database users. This permission can be granted with the command "GRANT SELECT ON mysql.user TO 'username'@'localhost' IDENTIFIED BY 'password';"
WARN  Users were not imported. 'userForSakila' will be set as the user name.
WARN  It was not possible to retrieve the list of all database permissions. Please ensure the current user has permissions to list all database permissions.

**User with no grants (not root user):**
PS C:\Users\laurir\Desktop\DBPTK> java "-Dfile.encoding=UTF-8" -jar dbptk-app-2.1.0-BETA.jar -i mysql --import-hostname=localhost -idb sakila -iu userForSakila -ip parool -e siar
d-2 -ef sakilaII.siard
      Converting database: mysql to siard-2
      Initializing database
Wed Feb 20 08:29:11 EET 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Wed Feb 20 08:29:11 EET 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
**ERROR Permission denied. Access denied for user 'userForSakila'@'localhost' to database 'sakila'**
      Log files and migration reports were saved in C:\Users\laurir\Desktop\DBPTK
      Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

**User with only select grant gets:**
ERROR Permission denied. SHOW VIEW command denied to user 'userForSakila'@'localhost' for table 'actor_info'

**User with only select, show view grant gets;**
no errors (sakilaIV.siard)

**User with all grants gets:**
no errors (sakilaV.siard)

sakilaIV.siard (6406 KB)
sakilaV.siard (6409 KB)
Should'nt these last two be the identical?

**Comment by chalkos** [comment]
I should remove this part

```
Wed Feb 20 08:29:11 EET 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Wed Feb 20 08:29:11 EET 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

MySQL JDBC Driver outputs that message without my consent...

-------------------

The other error messages seem fine to me, can I consider this task as completed for MySQL? (and proceed to implement similar error handlers for other DBMS)

-------------------

> **User with only select, show view grant gets;**
> no errors (sakilaIV.siard)
> 
> **User with all grants gets:**
> no errors (sakilaV.siard)
> 
> sakilaIV.siard (6406 KB)
> sakilaV.siard (6409 KB)
> Should'nt these last two be identical?

Maybe not.. send me the files (here or email) and I will check if this is a silent error (since no message was shown) or something else. If possible, I would also like to have the log file for these last 2 conversions.
