### ISSUE TITLE
Arrays are not supported

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#34]

**Comment by luis100** [comment]
@Chlara does the SIARD specification support arrays? How should an array be encoded in XML?

**Comment by Chlara** [comment]
@luis100 
The array is an issue (RFC 2014-110) for SIARD 2.0. The Issues are now published on the official eCH-Site: http://www.ech.ch/vechweb/page?p=dossier&documentNumber=eCH-0165&documentVersion=1.0 . 
Chlara

**Comment by luis100** [comment]
@Chlara in the meanwhile for SIARD 1.0, what should be the type of the column of an ARRAY type, or for any other unsupported type, like the PostgreSQL GIS types (e.g. polygon and circle)? 

Right now we are defining the column as CHARACTER VARYING(40) and dumping the textual serialization of the cell, which for something like a circle would become `<(1,1),1>`. But I guess it would be more proper to mark this column as of an UNSUPPORTED type, so when loading the SIARD database one could know what to expect (i.e. a simple textual dump of cell content). Is there anything already defined in SIARD? I could not find any clue on the specification.

**Comment by Chlara** [comment]
@luis100 
My Colleague @mkaiser56  will answer your question on Monday because I will be absent for one week.
Chlara
