### ISSUE TITLE
Handle databases with relations between schemas

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#340]
Relations between tables in different schemas are not handled correctly (or at all).

**Comment by chalkos** [comment]
I can not reproduce this.

My procedure:

1. I create a Postgres database with 2 schemas
2. create 1 table on each schema
3. each table has 2 columns.
    * first is the identifier (INT primary key not null autoincrement)
    * second is just an INT
4. created foreign key between schema2.table.col2 => schema1.table.col1
5. Added a couple of rows to test (worked fine)
6. Exported to SIARD

DBPTK did not output any errors and there weren't any errors in the log file. I checked the SIARD file and the foreign key was there, as well as the data.

@laurira can you double check if the beta1 version works?

**Comment by Laurira** [comment]
I tested with a database that has relations between schemas and it worked nicely.
