### ISSUE TITLE
Skip the import/export of specific columns

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#342]
Allow to skip certain columns when creating a SIARD file. Import can be optimized if the column is also skipped on import.

NOTE: Columns target or source of constraints (primary or foreign keys) that are to be ignored need also to be ignored.

**Comment by chalkos** [comment]
> NOTE: Columns target or source of constraints (primary or foreign keys) that are to be ignored need also to be ignored.

This was not a requirement iirc, and when implementing a similar feature (that skips the import/export of specific tables) this question about related elements being also skipped popped up and E-ARK (at least a part of it) decided it was better to let them be in the SIARD file.

When converting SIARD to a DBMS, invalid constraints are skipped and a warning is shown, so there is no harm done there.

**Comment by chalkos** [comment]
More information on using this feature: https://github.com/keeps/db-preservation-toolkit/wiki/List-Tables-Module

**Comment by Laurira** [comment]
**Very probable future scenario:** user wants to skip some tables or columns which caused DBPTK fatal error...

Now user have to create the list-tables but this also gives error....


At the moment I have three tables in my schema TESTING. DBPTK gets fatal error, I do not know why...
```
[oracle@localhost dbptk]$ java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.2.0-RC.jar --import=oracle --import-server-name=localhost --import-instance=orcl --import-username=testing --import-password=oracle --import-port-number=1521 --import-accept-license --export siard-2 --export-file=testing.siard
      Converting database: oracle to siard-2
      Initializing database
      Exporting SIARD version 2.1
      Obtaining table structure for TESTING.DO_EH_SP_PUNKT
      Obtaining table structure for TESTING.IMP_SD_162-01_41_19
ERROR Fatal error while converting the database (Invalid argument(s) in call)
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at /u01/userhome/oracle/dbptk/dbptk-report-20190418033850995.txt
      Log files and migration reports were saved in /u01/userhome/oracle/dbptk
      Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
```
This is the log
[testing.zip](https://github.com/keeps/db-preservation-toolkit/files/3093258/testing.zip)

What is the point of skipping tables if I can not skip tables which have errors?

**Comment by luis100** [comment]
@Laurira the objective of skipping table or columns was originally for anonymization purposes. The use case you describe was not part of the original requirements. Anyway, you could still produce the list of tables and columns manually and proceed with your work.

But, even if this issue was resolved or the manual list was produced, the process of extracting information from a database with problems in certain tables and trying to workaround it by selecting all tables except the ones with problems would still give errors because there are certain assumptions taken in the import of database metadata (as the database tables metadata is healthy), that would need to be made in a very different manner to cope with possible fatal failures in getting table descriptions even if the tables themselves were going to be skipped.

This to say, this should be in a different issue, that spawns a different requirement, that should be added to the roadmap for a following development project.

**Comment by Laurira** [comment]
Ok, you can add it for the future developments then. But what about the fatal error itself? Invalid arguments? What should this error tell to the user? Is it because my sdo_geometry has null values in it? Or is there some new issue?
