### ISSUE TITLE
Handle LOBs that exist outside the database

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#346]
If binary files are stored outside from the database (in file system) they should be handled like internal LOBs

- [x] base system to support the different types of external lobs
- [x] implementation: files on local filesystem

**Comment by luis100** [comment]
This will be implemented as a filter module. An abstract class will ease the development of new filter modules for different file access protocols (e.g. S3). A default implementation for file system access protocol will be implemented.

**Comment by Laurira** [comment]
Made first test with sakila database (mysql on windows)
```
I got java.lang.NullPointerException: null
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
```

This is how my database table with external lobs looks like
![error](https://user-images.githubusercontent.com/3479156/57123734-86258b80-6d8b-11e9-808e-ac1c7ab23aa1.JPG)

file path is `C:\Users\laurir\Desktop\DBPTK\SakilaPictureFolder\a13c4e637be4f4a33331ebbfe9c7956c.jpg`

Command that I executed
```
java "-Dfile.encoding=UTF-8" -jar .\dbptk-app-2.3.0-RC.jar -i mysql --import-hostname=localhost -idb sakila -iu root -ip parool -e siard-2 -ef sakila.siard -f external-lobs --filter1-reference-t
ype file-system --filter1-column-list .\sakilaListTablesWithExternalLobs
```

column list has one row in it
`sakila.customer{avatarFilePath;}`

**Did I do something wrong?**
At the moment the creation of siard fails when starting to convert the table customer.
