### ISSUE TITLE
SIARD: Simple ZIP data compression (8 Deflate) is now allowed

### ISSUE THREAD

**Issue by Chlara** [keeps/db-preservation-toolkit#35]
@luis100 
Hi Luis
With the SIARD-Addendum (Addendum_2015-01-23_eCH-0165_V1.0_SIARD-Formatspezifikation.pdf) a simple ZIP data compression (8 Deflate) is now allowed.
Linke to German Addendum: http://www.ech.ch/alfresco/guestDownload/attach/workspace/SpacesStore/7822a908-cf37-4146-9dab-90a5763380f2/Addendum_2015-01-23_eCH-0165_V1.0_SIARD-Formatspezifikation.pdf
Chlara

**Comment by chalkos** [comment]
fixed by #37
