### ISSUE TITLE
SIARD metadata editing

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#352]
For example users may want to add institution name to the siard etc.

**Comment by Laurira** [comment]
When user wants to see the list of edit then it is quite big
java "-Dfile.encoding=UTF-8" -jar dbptk-app-2.4.0-RC-4.jar edit -if sakilaCustom.siard -l

Can this be saved to a file?

**Comment by hmiguim** [comment]
You can redirect the output by using the '>' symbol. For instance:
java "-Dfile.encoding=UTF-8" -jar dbptk-app-2.4.0-RC-4.jar edit -if sakilaCustom.siard -l > list_of_metadata.txt

**Comment by Laurira** [comment]
Can you add this comment for directing the output to the help of dbptk?
java "-Dfile.encoding=UTF-8" -jar dbptk-app-2.4.0-RC-4.jar -h edit

**Comment by hmiguim** [comment]
Ok, its done.
