### ISSUE TITLE
Support connecting to DBMSs via an SSH tunnel with password authentication

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#370]
> Many databases reside in the servers which do not have graphical user interface at all. So my idea is that dbptk should not be executed in the same computer where the database is located. Instead we connect it via ssh tunnel which can be integrated to the DBPTK.

-- Lauri

**Comment by luis100** [comment]
Look into [JSch](http://www.jcraft.com/jsch/)

**Comment by hmiguim** [comment]
Close at 8dabd54

**Comment by Laurira** [comment]
Actually this task is not fully implemented.
#156 feature should also be considered.
Currently dbptk will not store files from outside of the database over SSH. The purpose of this feature #370 is that the dbptk should work as it is executed in the remote host.
Please add this addition to the feature.
