### ISSUE TITLE
Missing GML coordinates when migrating oracle to siard

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#371]
> I tested this with one of our institutions database which has SDO_GEOMETRY present.
> 
> I got following result in metadata.xml
> ```
> <column>
> 	<name>GEOMEETRIA</name>
> 	<lobFolder>lob7</lobFolder>
> 	<type>CHARACTER LARGE OBJECT</type>
> 	<typeOriginal>SDO_GEOMETRY</typeOriginal>
> 	<nullable>true</nullable>
> </column>
> ```
> But where is this lob folder `lob7`? It is not under content.
> And in Content -> table1.xml I have
> ```
> <row><c1>*****</c1><c2>2017</c2><c3>******</c3><c4>0.394</c4><c5>Põllusaar</c5><c6>2016.11.02 08:46:32</c6><c7>&lt;gml:Polygon&gt;
> \u0020\u0020&lt;gml:outerBoundaryIs&gt;
> \u0020\u0020\u0020\u0020&lt;gml:LinearRing&gt;
> \u0020\u0020\u0020\u0020\u0020\u0020&lt;gml:coordinates&gt;
> \u0020\u0020\u0020\u0020\u0020\u0020&lt;/gml:coordinates&gt;
> \u0020\u0020\u0020\u0020&lt;/gml:LinearRing&gt;
> \u0020\u0020&lt;/gml:outerBoundaryIs&gt;
> &lt;/gml:Polygon&gt;
> </c7></row><row><c1>*****</c1><c2>2017</c2><c3>*****</c3><c4>0.019</c4><c5>Põllusaar</c5><c6>2016.11.02 08:46:32</c6><c7>&lt;gml:Polygon&gt;
> \u0020\u0020&lt;gml:outerBoundaryIs&gt;
> \u0020\u0020\u0020\u0020&lt;gml:LinearRing&gt;
> \u0020\u0020\u0020\u0020\u0020\u0020&lt;gml:coordinates&gt;
> \u0020\u0020\u0020\u0020\u0020\u0020&lt;/gml:coordinates&gt;
> \u0020\u0020\u0020\u0020&lt;/gml:LinearRing&gt;
> \u0020\u0020&lt;/gml:outerBoundaryIs&gt;
> &lt;/gml:Polygon&gt;
> </c7></row>
> ```
> Where should be the coordinates?
> 

-- Lauri (see https://github.com/keeps/db-preservation-toolkit/issues/343#issuecomment-481982295)

**Comment by tomasmferreira** [comment]
I took a few rows from the example given (including the 2 rows that were causing an error while exporting) to ease the debugging phase. However, while trying to visualize the represented geometries in Oracle SQL Developer, I got the error message "Corrupted element info array" ('element info array' is part of the SDO_GEOMETRY data type).

![image](https://user-images.githubusercontent.com/11634630/56136579-fa3df200-5f8a-11e9-9e5d-4983e39fcbce.png)

**Comment by Laurira** [comment]
I have never used Oracle's "Map view" but it seems very limited and there is very little information in the internet about it.
Are you sure this is the way to validate geometry objects?

I tried with another database which contains row:
`MDSYS.SDO_GEOMETRY(2003, NULL, MDSYS.SDO_POINT_TYPE(658430.858589934, 6402602.69541891, NULL), MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null), MDSYS.SDO_ORDINATE_ARRAY(658430.58586118, 6402613.34979046, 658428.778577522, 6402612.55659944, 658424.232251351, 6402607.58413438, 658423.028006108, 6402605.32952996, 658422.221410305, 6402603.12175726, 658421.981432489, 6402599.0299194, 658422.406322712, 6402596.15969986, 658423.960531202, 6402593.67296628, 658426.447264787, 6402592.04104736, 658429.400260918, 6402592.04104736, 658432.897230021, 6402592.89586204, 658434.76228021, 6402594.45007052, 658437.17130337, 6402597.16993538, 658438.492380587, 6402598.95727515, 658439.502616105, 6402601.28858788, 658439.735747379, 6402603.69761104, 658438.259249313, 6402607.42771142, 658437.404434643, 6402609.68131373, 658435.927936577, 6402611.70178477, 658432.709478241, 6402613.21977309, 658430.58586118, 6402613.34979046, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null))`
and map view tells "The selected geometry is invalid and cannot be identified in the map view"

Are you sure that two first databases with sdo_geometry that I took from our institutions have invalid geometry? Should I ask them why they store invalid geodata? Or maybe there are better tools to validate oracle geodata?

**Comment by chalkos** [comment]
The application we use is Oracle SQL Developer https://www.oracle.com/database/technologies/appdev/sql-developer.html

We are obviously not sure yet if the data is invalid. It certainly has some characteristic that makes it different from other examples we have found, and this same characteristic is probably the cause for Oracle's application to say that something is corrupted. Despite this we were hoping to get more information before jumping to the conclusion that your institutions have invalid geometry.

**Comment by tomasmferreira** [comment]
After some searching I've concluded that the problem with the data is all those 'null' values at the end of the arrays.

From [oracle docs](https://docs.oracle.com/database/121/SPATL/sdo_geometry-object-type.htm#SPATL496): 
> The values in the SDO_ORDINATES array must all be valid and non-null. 

Same goes for SDO_ELEM_INFO (although not explicitly said).


After removing these null values, geometries could be opened in Map View and were correctly exported to the SIARD and GML files (using -egml parameter). Same with the example given here in comment.


What I suspect could have happened is that whatever was used to dump the data from the database introduced these 'nulls' in the arrays as some sort of padding.
Oracle validates the SDO_GEOMETRY structure but does not seem to validate some inner parts, and this allows for some nulls to be loaded without errors.

**Comment by chalkos** [comment]
Closing this since it is not a DBPTK problem.
