### ISSUE TITLE
SIARD 2.1 version folder (P_4.2-4)

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#376]
Just a small detail. In the new SIARD2.1 the folder called "header" should now contain a folder named "siardversion" and not "version" as previously. 

My observation is that DBPTK 2.3.0 RC still produces the old folder naming.  
See P_4.2-4 in SIARD 2.1

_Originally posted by @PhillipTommerholt in https://github.com/keeps/db-preservation-toolkit/issues/329#issuecomment-488607987_

**Comment by luis100** [comment]
@PhillipTommerholt can you please test it again using the updated DBPTK 2.3.0 RC?

**Comment by PhillipTommerholt** [comment]
@luis100 
I tested with DBPTK 2.3.0 RC, the .jar with MD5 checksum bab66354f37cb5801bbed7b326bfe84a and both for MySql and SQL server it produces the wrong folder name.

**Comment by tomasmferreira** [comment]
Because this issue was labeled as in milestone v2.4.0 it wasn't included in the previous release candidate.
It is now fixed in the [new release candidate](https://github.com/keeps/db-preservation-toolkit/releases/tag/v2.3.0-RC2).

**Comment by PhillipTommerholt** [comment]
Fixed in 2.3.0-RC2 :)
