### ISSUE TITLE
Double content for LOBs

### ISSUE THREAD

**Issue by solfeggietto** [keeps/db-preservation-toolkit#382]
Discovered bug in Decom v2.4.0-RC on the Total LOB path consisting of
Database lobFolder + Column lobFolder + Table row file attribute

As show below content/content gets doubled in DBPTK v2.4.0-RC as both Database lobFolder and Table row attribute file contains content inside. 

I suggest to implement the Column lobFolder (as this reduces redundancy) while reduce the file attribute parts. Or for now/faster simply remove the Database lobFolder element (keep redundancy repeat start path for every row of LOBs).

So far only tested Internal LOB, but i will add comments on External LOB tests when done.

[SIARD-Interoperability_2019-06-13 (Google spreadsheet)](https://docs.google.com/spreadsheets/d/1RRWtFQsRu02bxnHjlepM3f6DxRJ-9IQRt9cP7yEuQgY/edit#gid=148993364)

[SIARD-Interoperability_2019-06-14 (Google folder) - added all examples in subfolders](https://drive.google.com/drive/folders/1RKKC9yx9B576C0nCfyWofMIDvb9dh-6G)

DBPTK v2.3.0 implemented total LOB path like this (not according to SIARD 2.1 LOB path):
Database lobFolder = content
Column lobFolder = element not added (spec assumes . = same as Database lobFolder)
Table row file attribute = record2.bin

DBPTK v2.4.0 RC implements total LOB path like this:
Database lobFolder = content
Column lobFolder = element not added (spec assumes . = same as Database lobFolder)
Table row file attribute = content/schema1/table4/lob6/record2.bin

**Comment by luis100** [comment]
Fixed since 2.6.0
