### ISSUE TITLE
table[n].xml External LOB attribute messageDigest not SIARD 2.1

### ISSUE THREAD

**Issue by solfeggietto** [keeps/db-preservation-toolkit#383]
SIARD 2.1/2.1.1 spec section 6.2 Large Object Cells
table[n].xml column with External LOB reference
Attribute 1: digestType="MD5"
Attribute 2: digest="8AB663653CD42207F4F5C823569091F2" (example)

DBPTK v2.4.0-RC not according to SIARD 2.1/2.1.1 spec
table[n].xml column with External LOB reference
Attribute: messageDigestType="MD58AB663653CD42207F4F5C823569091F2" (example)
This is the old way done in SIARD 2.0 EARK

PS! The SIARD spec could have a default table.xsd with the available data-types and attributes to be reused by the different SIARD-tools, just as metadata.xsd is the key validator for metadata.xml. This bug above is not obvious beause the corresponding table[n].xsd validates although not according to SIARD 2.1/2.1.1 spec.

Completed all current tools with some earlier versions. Now added complete SIARD-files as well, including any External LOB folders in the tests.

[SIARD-Interoperability_2019-06-14 (Google spreadsheet all tests)](https://docs.google.com/spreadsheets/d/1RRWtFQsRu02bxnHjlepM3f6DxRJ-9IQRt9cP7yEuQgY/edit#gid=148993364)

[SIARD-Interoperability_2019-06-14 (Google folder, the files are in the subfolders)](https://drive.google.com/drive/folders/1RKKC9yx9B576C0nCfyWofMIDvb9dh-6G)

**Comment by luis100** [comment]
This is now solved since 2.6.0.
