### ISSUE TITLE
SIARD file generated by DBPTK-2.4.0-RC-3 are giving error when editing the metadata

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#384]
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3301636/dbptk-app.log.txt)
java -Xmx1000m -Dfile.encoding=UTF-8 -jar ..\dbptk-app-2.4.0-RC-3.jar edit -if 004_Izkaznice_IV_MNZ.siard --set dbname 'public'
      Edit SIARD metadata of 004_Izkaznice_IV_MNZ.siard
      Importing SIARD version 2.1
      Changing dbname from 'PUBLIC' to ''public''
      Metadata for dbname successfully updated
Exception in thread "main" java.lang.UnsupportedOperationException
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
        at java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at com.databasepreservation.modules.siard.out.update.MetadataUpdateStrategy.updateSIARDArchive(MetadataUpdateStrategy.java:96)
        at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.updateMetadataXML(SIARD21MetadataExportStrategy.java:157)
        at com.databasepreservation.modules.siard.update.SIARDEditModule.updateMetadata(SIARDEditModule.java:163)
        at com.databasepreservation.SIARDEdition.edit(SIARDEdition.java:122)
        at com.databasepreservation.Main.runEdition(Main.java:189)
        at com.databasepreservation.Main.internalMain(Main.java:122)
        at com.databasepreservation.Main.main(Main.java:73)

Attach the dbptk-app.log.txt file below.

**Comment by hmiguim** [comment]
Did you generate a new SIARD archive with this version (2.4.0-RC-3)?

**Comment by BorisDomajnko** [comment]
no, it was 2.3.0. But now I cannot do it with the new one. WHat am I doing wrong?

java -Xmx1000m -Dfile.encoding=UTF-8 -jar ..\dbptk-app-2.4.0-RC-3.jar -i microsoft-access -if Izkaznice_IV_MNZ.mdb -e siard-2 -ef 004_Izkaznice_IV_MNZ.siard

ERROR Command '-i' not a valid command.
Database Preservation ToolkitDatabase Preservation Toolkit (version 2.4.0-RC-3)
More info: http://www.database-preservation.com

Usage: dbptk COMMAND [OPTIONS]

Commands:

        migrate         Migrates data and metadata from an import module to an export module.
        edit            Edit the metadata information from a SIARD archive.

**Comment by hmiguim** [comment]
Since version 2.4.0 there is migrate and edit options, to do a migration you have to specify it. You just need to add the 'migrate' option on the command. Like so:
java -Xmx1000m -Dfile.encoding=UTF-8 -jar ..\dbptk-app-2.4.0-RC-3.jar **migrate** -i microsoft-access -if Izkaznice_IV_MNZ.mdb -e siard-2 -ef 004_Izkaznice_IV_MNZ.siard

**Comment by BorisDomajnko** [comment]
With the latest siard package it works. BTW, is this correct behavior?
After edit: <dbname>'public'</dbname>
Obviously I should not use '.

java -Xmx1000m -Dfile.encoding=UTF-8 -jar ..\dbptk-app-2.4.0-RC-3.jar edit -if 004_Izkaznice_IV_MNZ.siard --set dbname 'public'
      Edit SIARD metadata of 004_Izkaznice_IV_MNZ.siard
      Importing SIARD version 2.1
      Changing dbname from 'PUBLIC' to ''public''
      Metadata for dbname successfully updated
      Edit SIARD metadata took 0m 4s to complete.
      Log files and migration reports were saved in M:\Projekti\eARHsi\4_DBPTK
      Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

**Comment by hmiguim** [comment]
In this case you don't need to use apostrophe. You just need to use apostrophe if there is spaces involved, for instance, if you wanted to change the dbname to public from ms-access the name should be wrapped in apostrophes. 

I think is this what you are asking for.
