### ISSUE TITLE
Create SIARD of postgres fails, schema name error

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#387]
1.  I have a schema "sch_testA"
2.  I run java -Xmx1000m -Dfile.encoding=UTF-8 -jar dbptk-app-2.4.0.jar migrate -i postgresql -ih xxx -idb testA  ...  -e siard-2 -ef out.siard 
3.  I get ERROR: schema "sch_testa" does not exist

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3534139/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
Hi,
I tried to replicate the error but not with the same result.

For the database creation I follow this steps:
- create database "testA";
- create schema "sch_testA"

Then I run the DBPTK with this command: java -jar dbptk-app-2.4.0.jar migrate -i postgresql -ih localhost -iu postgres -ip 123456 -idb testA -ide -e siard-2 -ef sch_testA.siard

And all went good.

If you create the postgreSQL database and schema without the quotation, the database name is _testa_ and the schema name is _sch_testa_. Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case (https://www.postgresql.org/docs/current/sql-syntax-lexical.html).

In the screenshot below you can see the difference between quoting and unquoting the database or schema name.

![Screenshot-20190827170608-1920x1053](https://user-images.githubusercontent.com/1252710/63788359-3d22b580-c8ed-11e9-9d17-b6dafe963a56.png)

**Comment by BorisDomajnko** [comment]
Hi Miguel,
the schema is this: CREATE SCHEMA "sch_testA"
I tried with dbptk 2.0.0 and it works (as it used to work):

      Obtaining table structure for sch_testA.users
      ...
      Getting contents from table 'sch_testA.users'

If i try with 2.5.0-RC:
     Obtaining table structure for sch_testA.users
     ERROR Fatal error while converting the database

Log:
2019-08-28 10:48:44,509 [main] DEBUG (c.d.m.Reporter) failedToGetDescription, message: - Information: could not get description for constraint (`sch_testA.users.primary_index`)
org.postgresql.util.PSQLException: ERROR: schema "sch_testa" does not exist

**Comment by hmiguim** [comment]
Hi Boris,

Could you provide the SQL instructions that you used to create the database?

**Comment by hmiguim** [comment]
Nevermind, I could replicate the error

**Comment by hmiguim** [comment]
Good news, I found what causes the error, and it's currently fixed. I'll run some tests to make sure that's it.

**Comment by hmiguim** [comment]
@BorisDomajnko, in the next relase (2.5.0) the bug will be fixed

**Comment by BorisDomajnko** [comment]
Checked, it is ok with 2.5.0:
     . . .
      Completed schema 'sch_testA' (2 of 2 schemas completed)
      Completed database migration
    . . .
Regards, Boris
