### ISSUE TITLE
2.6.0-RC - SIARD can't validate - possibly due to empty table

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#395]
Description: 
Validation stops unexpected after table2 with following error:    
>  P_4.3-6: [SKIPPED]
>       P_4.3-7: [START]
>       content/schema1/table1/table1.xml
>       content/schema1/table2/table2.xml
> Exception in thread "main" java.lang.NullPointerException
>         at com.databasepreservation.modules.siard.validate.component.formatStructure.MetadataAndTableDataValidator.validateNillableInformation(MetadataAndTableDataValidator.java:657)
>         at com.databasepreservation.modules.siard.validate.component.formatStructure.MetadataAndTableDataValidator.validate(MetadataAndTableDataValidator.java:231)
>         at com.databasepreservation.modules.siard.validate.SIARDValidateModule.validate(SIARDValidateModule.java:118)
>         at com.databasepreservation.SIARDValidation.validate(SIARDValidation.java:106)
>         at com.databasepreservation.Main.runValidation(Main.java:192)
>         at com.databasepreservation.Main.internalMain(Main.java:129)
>         at com.databasepreservation.Main.main(Main.java:76)
> 
It might have to do with the fact that table3.xml does not have content
Steps required to reproduce the bug:

1. I have an example database on a SQL Server
2. I use 2.6.0-RC to create a SIARD-file (runs successfully)[northwind26.siard.zip](https://github.com/keeps/db-preservation-toolkit/files/3600778/northwind26.siard.zip)
3. I use 2.6.0-RC to validate the output (se error message above from cmd prompt)
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3600785/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
I'll look into it.

**Comment by hmiguim** [comment]
> It might have to do with the fact that table3.xml does not have content
You're right.

There is also another validation that produces the same error, already fixing it.
