### ISSUE TITLE
2.6.0-RC (2.5.0 too) - SIARD can´t be deployed to PostgreSQL 

### ISSUE THREAD

**Issue by MartinR4838** [keeps/db-preservation-toolkit#396]
Description: 
SIARD file was validly produced but migration to PostgreSQL generates errors and is data loss. 
Steps required to reproduce the bug:

1. MSSQL Server 2012 express, DB size (bak file) ~ 6,6 GB, File storage in DB
2. DBPTK 2.6.0-RC (2.5.0)
3. PostgreSQL 4.11

Best regards
Martin

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3600903/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
> Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "PK_DOKUMENT_KOPIE_POHYB"
  Detail: Key ("ID_DOKUMENT_KOPIE_POHYB")=(41) already exists.

The error comes from PostgreSQL

**Comment by MartinR4838** [comment]
Thanks.
Martin

**Comment by MartinR4838** [comment]
DBVTK migrates same SIARD to PostgreSQL smoothly without errors.
Thanks!
Martin
