### ISSUE TITLE
LOB options: Schema referenced in column list file, was not found in the database

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#397]
I wanted to test external LOBs.
In wiki text "External LOBs Filter Module" there is only a description of creating a siard package. It is not clear how to export back to the database: is the filesystem folder content included in the package or not, how to extract it...

Creating of siard package is ok without the LOB options. But this scenario has problems:

LOB_list_file.txt:
`"AirplanesLinks"."models"{picture;}`

Command:
```
java -Xmx1000m -jar dbptk-app-2.6.0-RC.jar migrate \
-f external-lobs --filter1-reference-type file-system --filter1-column-list /home/doma/dbdipview/www/files/LOB_list_file.txt  ...
```
Error:  Schema "AirplanesLinks", referenced in column list file, was not found in the database
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3605042/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
Hi Boris,

The issue is fixed. Although you need to cut the double quotes from the LOB_list_file.txt.

Instead of this:

**Comment by BorisDomajnko** [comment]
Hi, I have modified the only (!)  line in the file:

LOB_list_file.txt:
`AirplanesLinks.models{picture;}`

It seems to work now, but now I get an error with another table: "HR database", which makes no sense. If I run dbptk without lob filter, it runs ok.

```
-jar dbptk-app-2.6.0-RC.jar migrate \
-f external-lobs --filter1-reference-type file-system \
--filter1-column-list /home/doma/dbdipview/www/files/LOB_list_file.txt \
--filter1-base-path=/home/doma/dbdipview/www/files/TestAndDemo1 
```
```
      Migrating schema 'AirplanesLinks' (0 of 3 schemas completed)
      Migrating table 'models' (0 of 1 tables completed)
      Completed table 'models' (1 of 1 tables completed)
      Completed schema 'AirplanesLinks' (1 of 3 schemas completed)
      Migrating schema 'HR database' (1 of 3 schemas completed)
ERROR Fatal error while converting the database (Unrecognized schema name HR database)
```
Regards, Boris

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3616227/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
Hi Boris,

The issue is fixed but not present yet in any release, only when the release of version 2.6.0.

I was pointing out the malformed line for the filter column list file.

If you want to test it out, I can provide a SNAPSHOT version with the patch. Otherwise you will have to wait for the final release.

**Comment by BorisDomajnko** [comment]
I removed public and HR database schema and was then able to continue with this test scenario, but now I have a problem with deployment of the siard file (#398) , so there are more issues to be resolved. If both errors can be tested with SNAPSHOT, I can do it.
