### ISSUE TITLE
Unexpected exception (null)

### ISSUE THREAD

**Issue by Johan-Ekdahl** [keeps/db-preservation-toolkit#402]
Description: Getting a "Unexpected exception (null)" when trying to create a SIARD-file with dbptk-app-2.6.0.jar, the same problem with dbptk-app-2.5.0.jar but dbptk-app-2.4.0.jar works fine.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3706478/dbptk-app.log.txt)

Steps required to reproduce the bug:

1. 
2. 
3. 

Attach the dbptk-app.log.txt file below.

**Comment by luis100** [comment]
There is a NPE guard missing at https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-modules/dbptk-module-sql-server/src/main/java/com/databasepreservation/modules/sqlServer/SQLServerExceptionNormalizer.java#L36


Although that is only masking another exception, but without it we wont be able to diagnose.

**Comment by hmiguim** [comment]
@Johan-Ekdahl The NPE guard was added. Even though, the connection problem will remain, because you specified the port number alongside the server-name, to solve that you need to use the option: --import-port-number <value>.

**Comment by hmiguim** [comment]
Closed at 8015da6

**Comment by Johan-Ekdahl** [comment]
Thank you for your answer, I will try the --import-port-number option
and check if that resolve our problem.

Best regards 
Johan 

Johan Ekdahl

Riksarkivet/Swedish National Archives
Enheten för ljud, bild och elektroniska arkiv (ELBE)/The Unit for
Audiovisual and Electronic Archives
Box 12541
102 29 Stockholm
tel +46(0)10 476 70 00 ( tel:+460104767000 )
tel dir +46 10 476 71 37
johan.ekdahl@riksarkivet.se 
 




>>> Miguel Guimarães <notifications@github.com> 2019-10-14 17:39 >>>
@Johan-Ekdahl The NPE guard was added. Even though, the connection
problem will remain, because you specified the port number alongside the
server-name, to solve that you need to use the option:
--import-port-number <value>.
