### ISSUE TITLE
dbptk migration - microseconds should not be rounded

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#409]
One of our institution has a primary key which is composite consisting of code and time.

In the original database we have:
616d71c8831671c8464d28c70b0f11  2014-12-19 08:25:03.671011
616d71c8831671c8464d28c70b0f11  2014-12-19 08:25:03.671966 

DBPTK creates
<c1>616d71c8831671c8464d28c70b0f11</c1><c2>2014-12-19T06:25:03.671Z</c2>
<c1>616d71c8831671c8464d28c70b0f11</c1><c2>2014-12-19T06:25:03.671Z</c2>

And the key is broken...

**Comment by luis100** [comment]
Maybe this can be of help: https://stackoverflow.com/a/10073872/12227642
