### ISSUE TITLE
log file and -ide (disable encryption) parameter

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#411]
The app "dbptk-app-2.6.1.jar .... -ide ..." created report "dbptk-report-20191105184949587.txt".
In that reort there are -disable-encryption = false

If the "-ide" parameter is not present then log file contains "disable-encryption = true"

So shouln't it be the other way around?

**Comment by hmiguim** [comment]
It should

**Comment by hmiguim** [comment]
Closed at 60188ae
