### ISSUE TITLE
Validation doesn´t finish

### ISSUE THREAD

**Issue by MartinR4838** [keeps/db-preservation-toolkit#416]
Description: 

Steps required to reproduce the bug:

1. DBPTK 2.6.2
2. SIARD 6GB (inside cca 74GB
After one day it is still running? or freeze

Attach the dbptk-app.log.txt file below.

**Comment by luis100** [comment]
@MartinR4838 can you provide the log, or at least the last 1000 lines of it? In which step is it right now?

Please note that by default the validation does a set of [additional checks](https://github.com/keeps/db-preservation-toolkit/wiki/Validation#additional-checks), one of them does a complete referential integrity check which can take a lot of time on a very large database. This uses a embedded database file that might grow a lot, see the [wiki](https://github.com/keeps/db-preservation-toolkit/wiki/Application-usage#mapdb-options) for more info.

**Comment by MartinR4838** [comment]
Hello,
thanks for reply, Yeas I´m aware of this and I hope it is still running (more than 27 hours), migration to PostgreSQL took 15 hours. Now i DBPTK validating primary keys T_6.0.-1 on biggest table
![command_line](https://user-images.githubusercontent.com/54624927/68854987-91178c00-06dd-11ea-88f4-71a16abcb530.jpg)
[dbptk-app-2019-11-13.0.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3846315/dbptk-app-2019-11-13.0.log.txt)

**Comment by MartinR4838** [comment]
Good news, validation is still running and may be on monday it will be done. 
Best regards

**Comment by MartinR4838** [comment]
Hello, now I can report that validation is done.
