### ISSUE TITLE
Problems with data type conversion - validation Float x Double Precision v.2.6.0

### ISSUE THREAD

**Issue by MartinR4838** [keeps/db-preservation-toolkit#417]
Description: Data Type Float not converted to Double Precision

The data type information on the column definitions in metadata.xml must be identical to that in the corresponding table[number].xsd file - For 'DOUBLE PRECISION' type expected 'xs:double' but found 'xs:float'. SIARD file is not valid but migration is possible. 
![c18](https://user-images.githubusercontent.com/54624927/68846052-b51ea180-06cc-11ea-9b62-8c9fe9d4461c.jpg)
![c19](https://user-images.githubusercontent.com/54624927/68846053-b5b73800-06cc-11ea-8d72-5be31520acff.jpg)
![c20](https://user-images.githubusercontent.com/54624927/68846055-b5b73800-06cc-11ea-88ec-8cc09f1314d7.jpg)
[Extract_migrate_validate_reports - v2_6_0.txt](https://github.com/keeps/db-preservation-toolkit/files/3845774/Extract_migrate_validate_reports.-.v2_6_0.txt)

Kind regards
Martin

**Comment by hmiguim** [comment]
Martin, version 2.6.0 had an issue doing the conversion of SQL 2008 type to XSD type. This was fixed on version 2.6.1 (3e58489d2c8217a03bb0e7859dec33fd383d164b). Before it converted to XSD type xs:float, but the SIARD 2.1 version specification requires that it was converted to xs:double.

**Comment by MartinR4838** [comment]
Miguel,

thanks for reply. A was waiting with validation for v 2.6.2. and producer will not be happy to produce such big SIARD again. 

Kind regards
M.R.

**Comment by hmiguim** [comment]
Martin, If you do the migration SIARD to SIARD with the newer version conversion error will be fixed.

**Comment by MartinR4838** [comment]
Thank you Miguel. I will do it but first must wait on the end validation :-).

Kind regards
