### ISSUE TITLE
Problem recreating database from SIARD file

### ISSUE THREAD

**Issue by DavidUnderdown** [keeps/db-preservation-toolkit#418]
Description: As part of my testing of #338 I wanted to recreate the database from the SIARD file so that I could directly compare the original database to another SQL server database.  Table creation is failing.

Steps required to reproduce the bug:

1. For the most part I've just flipped import to export (and vice-versa) in my command line invocation, so I'm running (with some details redacted):
`java -jar "-Dfile.encoding=UTF-8" "Q:\Digital Preservation Team\PRONOM SIARD\DBPTK\dbptk-app-2.6.2.jar" migrate --export microsoft-sql-server --export-server-name=<server-name> --export-port-number=4333 --export-database="DMO_DWH_FROM_SIARD" --export-username="%_username%" --export-password="%_password%" -ede --import siard-2 --import-file="Q:\Digital Preservation Team\PRONOM SIARD\UKDM1HB001\UKDM_1\content\2019-15-10-DMO_DWH.siard"`
2. It connects to the database OK, but for each execution of CREATE TABLE, I'm getting the message:
`2019-11-12 10:42:42,936 [main] DEBUG (c.d.m.Reporter) something failed, message: - Information: Execution of query ``CREATE TABLE [dbo].[VIEW_View_TBILL_ISSUANCE_HISTORY] ([MATURITY_DATE] datetime2 NULL, [ISIN_CODE] varchar(80) NULL, [INSTRUMENT_NAME] varchar(500) NULL, [INSTRUMENT_TYPE] varchar(10) NULL, [ISSUE_METHOD] char(2) NULL, [FIRST_ISSUE_DATE] datetime2 NULL, [PARENT_AMOUNT_ISSUED] decimal(28,10) NULL, [FIRST_REOPENING_AMOUNT] decimal(28,10) NULL, [SECOND_REOPENING_AMOUNT] decimal(28,10) NULL, [PARENT_ISSUE_DATE] datetime2 NULL, [FIRST_REOPENING_DATE] datetime2 NULL, [SECOND_REOPENING_DATE] datetime2 NULL, [AMOUNT_OUTSTANDING] decimal(28,18) NULL, [TotalAmount] decimal(28,2) NULL, [ADHOC_AMNT] decimal(28,2) NULL)`` failed because of the following error: Line 1: Specified scale -4 is invalid.`

Attach the dbptk-app.log.txt file below: the file is many megabytes as the failure of table creation was then leading to all the INSERTs to fail too.  Hopefully there's enough above to pin-point the issue, but I can add larger extracts if necessary.

**Comment by hmiguim** [comment]
Hi David,

I tried to replicate the error, but without any success. I used SQL Server 2017 instance, create the table with the above statement and populate with data, export to SIARD and import back again to the SQL Server, but the whole process run without any failure. I used the same DBPTK version as well. Could you provide more information, maybe the SQL Server version, to rule out some possibilities.

**Comment by DavidUnderdown** [comment]
Looks like it's still SQL 2012 - it's an old dev server.

Presumably the command itself looks OK, I've not omitted anything I shouldn't have - the documentation doesn't seem to be quite up-to-date so I was having to use a bit of trial and error to work out what I needed to do.

**Comment by hmiguim** [comment]
I'll try to install the SQL 2012 version and see if I can recreate the issue.

One question, that is the first occurrence of the error?

**Comment by DavidUnderdown** [comment]
There were a couple of essentially identical ones beforehand:

> 2019-11-12 10:42:42,880 [main] DEBUG (c.d.m.j.o.JDBCExportModule) Executing table creation batch
> 2019-11-12 10:42:42,916 [main] DEBUG (c.d.m.j.o.JDBCExportModule) Got a batch update exception while executing a batch statement
> java.sql.BatchUpdateException: Line 1: Specified scale -4 is invalid.
> 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeBatch(SQLServerStatement.java:1749)
> 	at com.databasepreservation.modules.jdbc.out.JDBCExportModule.statementExecuteAndClearBatch(JDBCExportModule.java:904)
> 	at com.databasepreservation.modules.jdbc.out.JDBCExportModule.handleStructure(JDBCExportModule.java:366)
> 	at com.databasepreservation.model.modules.filters.IdentityFilter.handleStructure(IdentityFilter.java:77)
> 	at com.databasepreservation.model.modules.filters.ObservableFilter.handleStructure(ObservableFilter.java:78)
> 	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.migrateDatabaseTo(SIARDImportDefault.java:58)
> 	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:102)
> 	at com.databasepreservation.Main.runMigration(Main.java:295)
> 	at com.databasepreservation.Main.internalMain(Main.java:122)
> 	at com.databasepreservation.Main.main(Main.java:76)
> 2019-11-12 10:42:42,919 [main] ERROR (c.d.m.j.o.JDBCExportModule) Error executing query: CREATE TABLE [dbo].[VIEW_vw_Gilts] ([INSTRUMENT_ID] int NULL, [INSTRUMENT_NAME] varchar(500) NULL, [ISIN_CODE] varchar(80) NULL, [MATURITY_DATE] datetime2 NULL, [INSTRUMENT_TYPE] varchar(10) NULL, [INSTRUMENT_TYPE_DESCRIPTION] varchar(80) NULL, [INDEXATION_LAG] varchar(8) NOT NULL, [RUMP_FLAG] char(1) NULL, [MATURITY_BRACKET] varchar(40) NULL, [ACTUAL_DATE] datetime2 NULL, [LAST_BUSINESS_DATE] datetime2 NULL, [FIRST_ISSUE_DATE] datetime2 NULL, [SETTLEMENT_DATE] datetime2 NULL, [BASE_RPI_87] decimal(28,18) NULL, [CURRENT_EX_DIV_DATE] datetime2 NULL, [FINAL_EX_DIV_DATE] datetime2 NULL, [DIVIDEND_DATE_TEXT] varchar(40) NULL, [AMOUNT_OUTSTANDING] decimal(28,18) NULL, [AMOUNT_OUTSTANDING_PLUS_IL_UPLIFT] decimal(28,7) NULL, [UndatedNonRumpCount] int NULL)
> 2019-11-12 10:42:42,922 [main] DEBUG (c.d.m.Reporter) something failed, message: - Information: Execution of query ``CREATE TABLE [dbo].[VIEW_vw_Gilts] ([INSTRUMENT_ID] int NULL, [INSTRUMENT_NAME] varchar(500) NULL, [ISIN_CODE] varchar(80) NULL, [MATURITY_DATE] datetime2 NULL, [INSTRUMENT_TYPE] varchar(10) NULL, [INSTRUMENT_TYPE_DESCRIPTION] varchar(80) NULL, [INDEXATION_LAG] varchar(8) NOT NULL, [RUMP_FLAG] char(1) NULL, [MATURITY_BRACKET] varchar(40) NULL, [ACTUAL_DATE] datetime2 NULL, [LAST_BUSINESS_DATE] datetime2 NULL, [FIRST_ISSUE_DATE] datetime2 NULL, [SETTLEMENT_DATE] datetime2 NULL, [BASE_RPI_87] decimal(28,18) NULL, [CURRENT_EX_DIV_DATE] datetime2 NULL, [FINAL_EX_DIV_DATE] datetime2 NULL, [DIVIDEND_DATE_TEXT] varchar(40) NULL, [AMOUNT_OUTSTANDING] decimal(28,18) NULL, [AMOUNT_OUTSTANDING_PLUS_IL_UPLIFT] decimal(28,7) NULL, [UndatedNonRumpCount] int NULL)`` failed because of the following error: Line 1: Specified scale -4 is invalid.

**Comment by hmiguim** [comment]
Can you share the log with me via email? According to the log you send me and some research on the topic, my guess is one of the create table statement has an error with precision, however they are created in batch, and without looking all the create statements I can figure it out which one is.

**Comment by DavidUnderdown** [comment]
I've cut out the table creation statements from the rest of the log (the full log is 35mb, well the first part of it) and I'll email that.

**Comment by hmiguim** [comment]
From the logs with was determined that DBPTK when migrating to SQL Server is transforming the type decimal(38,6) to decimal(28,-4).

**Comment by hmiguim** [comment]
Next version (2.6.4) will include the fix.
