### ISSUE TITLE
NPE when validating a SIARD file foreign keys

### ISSUE THREAD

**Issue by hmiguim** [keeps/db-preservation-toolkit#423]
Example, when you create a SIARD and export only a certain amount of tables, if the table has a foreign key and the reference table was not exported it gives an NPE when validating the SIARD.

**Comment by hmiguim** [comment]
Possible solution:

* show an **warning** saying: 'No primary data for foreign key 'foreign_key_name' on content/schema1/table1/table1.xml' and the validation step is **valid**. 

* Or show an **error** saying: 'Could not validate the foreign key data for foreign key 'foreign_key_name' on content/schema1/table1/table1.xml and the validation step is **invalid**. 

@Laurira can you give a feedback about this?

**Comment by Laurira** [comment]
We would prefer the option 1: "warning".

**Comment by hmiguim** [comment]
option 1 it is

**Comment by hmiguim** [comment]
Close at ce58b82
