### ISSUE TITLE
Character code on input

### ISSUE THREAD

**Issue by MartinR4838** [keeps/db-preservation-toolkit#430]
Is there chance to convert chararacter code using DBPTK to UTF-8? We have many old Access DBs which have original character code ISO-8859-2 or Windows-1250/Win Latin 2

Description: 
Table in SIARD looks like this:
c10>Spr�va �elezni�n� dopravn� cesty, st�tn� organizace</c10><c11>70994234</c11><c12>st�tn� oraganizace</c12><c13>Dl�d�n� 1003/7</c13><c14>Praha 1, Nov� M�sto</c14>
We need this:
c10>Správa železniční dopravní cesty, státní organizace</c10><c11>70994234</c11><c12>státní oraganizace</c12><c13>Dlážděná 1003/7</c13><c14>Praha 1, Nové Město</c14>

Czech language is full of diacritics.
Thanks!

**Comment by hmiguim** [comment]
When you generate the SIARD did you include the option "-Dfile.encoding=UTF-8"?

**Comment by MartinR4838** [comment]
Yes, I did.

"java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.6.4.jar migrate -i microsoft-access -if  C:\DBPTK\olup.mdb -e siard-2 -ef C:\dbptk\olup.siard"

**Comment by hmiguim** [comment]
Do you have a small sample that you can provide for us to test it?

**Comment by MartinR4838** [comment]
Yes, I can but it need some redaction. Original file is from year 2001 and I have only Access 2010. But also accdb conversion has same character result after migration to SIARD. 
Thanks

**Comment by MartinR4838** [comment]
Thanks for help although it was without success.

**Comment by MartinR4838** [comment]
Small sample for your tests.
Thank you.

[test_olup.zip](https://github.com/keeps/db-preservation-toolkit/files/4235165/test_olup.zip)

**Comment by MartinR4838** [comment]
[test_olup_mdb.zip](https://github.com/keeps/db-preservation-toolkit/files/4235189/test_olup_mdb.zip)
