### ISSUE TITLE
dbptk developer - version 2.8.1 - confusion with modules

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#442]
Is it intentional that you do not have list-tables in the export modules any more?
Also under the "Export modules" there is "import-config"
![image](https://user-images.githubusercontent.com/3479156/78763571-fa01e800-798d-11ea-93ff-4def2eaae37f.png)

**Comment by hmiguim** [comment]
Hi Lauri,

Upon the release of version 2.7.0 we explain that list-tables was replaced by this import-config module. You can consult out wiki page to see more information about this new module. https://github.com/keeps/db-preservation-toolkit/wiki/Import-Config-Module

**Comment by Laurira** [comment]
Ok, thanks. I did not noticed that explanation. Actually that all makes sense

**Comment by hmiguim** [comment]
Closing this issue
