### ISSUE TITLE
Missing customized views

### ISSUE THREAD

**Issue by martenlindstrandx** [keeps/db-preservation-toolkit#446]
We are trying to cerate custom views for the first time and have defined, tested and saved 3 views before creating SIARD-file. When creation process is done, only one of the custom views is present when browsing the SIARD. 

The created siardfile contains only one view, the latest we wrote and saved in the create phase:
strings systemx.siard |grep -i CUSTOM_VIEW|sort -u
                    <name>CUSTOM_VIEW_Diarieplan</name>

Any ideas why?

**Comment by hmiguim** [comment]
Can you provide more information? Which version of DBPTK did you use to create the SIARD?

**Comment by martenlindstrandx** [comment]
Latest, DBPTK, Version 2.4.1 , what kind of patterns from logfiles are useful to provide?

**Comment by hmiguim** [comment]
Closed and moved to https://github.com/keeps/db-visualization-toolkit/issues/211 (problem is related with Desktop application)
