### ISSUE TITLE
Need SIARD support

### ISSUE THREAD

**Issue by tlauritzen** [keeps/db-preservation-toolkit#5]
Hi.

I need to have SIARD support integrated into the db-preservation-toolkit. I can see, that there is already a pull request for such a feature: https://github.com/keeps/db-preservation-toolkit/pull/3

Would you please consider merging this int the toolkit? I am using an Alfresco database for testing, and I might as well test the SIARD support as well :-)
- Torben/e-ark

**Comment by Chlara** [comment]
The eCH-0165 SIARD Format Specification v1.0 is now available in English: http://www.ech.ch/alfresco/guestDownload/attach/workspace/SpacesStore/3b8dc8fb-d5df-4748-91f9-23c124b0f275/STAN_e_DEF_2015-02-04_eCH-0165_V1%200_SIARD-Format.pdf
