### ISSUE TITLE
Needed: Working example for rc

### ISSUE THREAD

**Issue by stumpdk** [keeps/db-preservation-toolkit#70]
Maybe it's just me, but I can't get the newest version to work with the example given in the readme.

I use these parameters:

java -jar db-preservation-toolkit-2.0.0-jar-with-dependencies.jar -i MySQLJDBC -ihostname=127.0.0.1 -idatabase=mydatabase -iusername=root -ipassword=somepassword iport-number=3306 -o SIARD example.siard

And get this error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-
idatabase=kbharkiv"

**Comment by andersbonielsen** [comment]
Hej Bo

Hvis du har brug for en dansk kontaktperson, så kan du skrive til mig.
Jeg har også kontakten til danske Magenta, som står for at lave en variant af db-preservation-toolkit, så den lettere (ikke 100%) kan anvendes med bek. 1007.

[cid:image001.jpg@01D0FA0B.A19846C0]
Anders Bo Nielsen
chefkonsulent
Indsamling og Bevaring


Telefon: 33 92 33 10  | Direkte: 41 71 72 35
abn@sa.dk<mailto:abn@sa.dk>  |  www.sa.dk<http://www.sa.dk>

Fra: Bo Henriksen [mailto:notifications@github.com]
Sendt: 28. september 2015 16:31
Til: keeps/db-preservation-toolkit
Emne: [db-preservation-toolkit] Needed: Working example for rc (#70)


Maybe it's just me, but I can't get the newest version to work with the example given in the readme.

I use these parameters:

java -jar db-preservation-toolkit-2.0.0-jar-with-dependencies.jar -i MySQLJDBC -ihostname=127.0.0.1 -idatabase=mydatabase -iusername=root -ipassword=somepassword iport-number=3306 -o SIARD example.siard

And get this error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "-
idatabase=kbharkiv"

**Comment by stumpdk** [comment]
Hej Anders Bo
Er den danske udgave open source, og hvis ikke, er der en grund til, at de ikke bidrager til Database Preservation Toolkit i stedet?

Venlig hilsen Bo

**Comment by chalkos** [comment]
@stumpdk The releases were out of date. I have added a new release based on the most recent version of the code: https://github.com/keeps/db-preservation-toolkit/releases/tag/2.1.1

**Comment by luis100** [comment]
@stumpdk support for the Danish version of SIARD, being developed by Magenta, is going to be merged into the main version of this tool soon. Please note that none of the input/output modules of SIARD (versions 1.0, DK and 2.0)  is final, we are still undergoing development. So please take this under consideration when testing the tool.

**Comment by stumpdk** [comment]
Thank you very much for the new release. It works like a charm!

**Comment by stumpdk** [comment]
I look forward to the danish implementation of the Siard standard.

Thanks again for your reply.
