### ISSUE TITLE
Add a graphical user interface

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#86]
Add a GUI to the dbptk, which includes all features of CLI.
The GUI should open when the jar is called with no parameters.
Normal syntax will only be shown when jar is called with -h or --help

**Comment by luis100** [comment]
Interface can follow the mockup available at [db-preservation-toolkit GUI.pdf](https://github.com/keeps/db-preservation-toolkit/files/28794/db-preservation-toolkit.GUI.pdf).

A prototype implementation of the mockup is available at [db-preservation-toolkit-gui](https://github.com/keeps/db-preservation-toolkit-gui).

**Comment by Laurira** [comment]
I was started thinking that many db-s need ssh tunnel to connect. Many servers do not have graphical view at all so first the GUI should create SSH tunnel and then we can set the db connection parameters...

**Comment by luis100** [comment]
SSH tunnel issue added at #370

**Comment by luis100** [comment]
To use JavaFX to create the GUI. Best option for compatibility, less base dependencies (still Java), modern (at least more modern than Swing/AWT), and developers already have experience on it.

Two options:
1. Include in the base application, if dbptk.jar is called without arguments, or simply double-clicked, it will open the GUI. This will require the dbptk java version compatibility to be set to java 8 (previously java 7). This will also allow some improvements in another parts of the code.
2. Available in a different application that will use dbptk as a library. Will allow to continue using dbptk base CLI with Java 7 and separate code into two projects/modules. The result will be two jars, one for CLI and another for GUI.

@Laurira any comment or preferred option?

**Comment by luis100** [comment]
Note: as with [RODA-in](https://github.com/keeps/roda-in/releases) we can also automatically make a alternative .exe version to be more easily used in Windows.

**Comment by luis100** [comment]
This was done at https://github.com/keeps/db-visualization-toolkit and has releases at https://github.com/keeps/db-visualization-toolkit-electron
