### ISSUE TITLE
Column type change in PostgreSQL

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#9]
When round-trip testing PostgreSQL to SIARD and back again, the following column data types change:
* `character varying` becomes `text`
* `bigint` becomes `numeric(19,0)

**Comment by chalkos** [comment]
#60 adds support for these changes so the roundtrip test expects the type to change from `character varying` to `text`, `bigint` to `numeric(19,0)`, etc

that pull request only fixes one postgreSQL problem (`"char"` becoming `character(1)`), but it makes it trivial to add more rules for the other two cases in here.

**Comment by chalkos** [comment]
```numeric(10,2)``` becomes ```numeric``` in PostgreSQL
