### ISSUE TITLE
Better output from the CLI

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#94]
Make a better output of CLI by using two appenders in Log4J:
* Make logs of error messages become two logs: one of level ERROR and with a small but insightful message into the error, and another of level DEBUG and with the stack-trace.
* Make two appenders and two loggers, one for STDOUT with level INFO and with a pattern optimized for users: no milliseconds, no class names; and another for FILE with level DEBUG and with a pattern optimized for debugging.

**Comment by chalkos** [comment]
Fixed by #100
