### ISSUE TITLE
Avoid failure when user does not have permissions to access the users list

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#95]
Right now, for DBPTK to be able to get the users to put on SIARD it needs access to some privileged tables that list all users. Change this so it does not fail on the user does not have permission to access this information.

Current needed special permissions:
```sql
GRANT SELECT ON mysql.user TO '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT SELECT ON mysql.tables_priv TO '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
```

**Comment by chalkos** [comment]
Same happens in Postgresql

**Comment by luis100** [comment]
The issue still remains as it fails when use does not have permissions to access table 'tables_priv' on the mysql database.

```
ERROR [14:44:49] It was not possible to retrieve the list of all database permissions. Please ensure the current user has permissions to list all database permissions.
                 SELECT command denied to user 'ratsep'@'172.18.20.206' for table 'tables_priv'
```

**Comment by chalkos** [comment]
That ERROR is not fatal and is ignored, behaving more like a WARNING.
When the user does not have permissions to list database permissions the application ignores that part.
